#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("P_arr_x_address0", 7, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("P_arr_x_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("P_arr_x_q0", 16, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("P_arr_y_address0", 7, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("P_arr_y_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("P_arr_y_q0", 16, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("P_arr_z_address0", 7, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("P_arr_z_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("P_arr_z_q0", 16, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("K_arr_address0", 7, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("K_arr_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("K_arr_q0", 16, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("B_i_address0", 5, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("B_i_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("B_i_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("B_i_d0", 32, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("B_i_address1", 5, hls_out, 4, "ap_memory", "MemPortADDR2", 1),
	Port_Property("B_i_ce1", 1, hls_out, 4, "ap_memory", "MemPortCE2", 1),
	Port_Property("B_i_we1", 1, hls_out, 4, "ap_memory", "MemPortWE2", 1),
	Port_Property("B_i_d1", 32, hls_out, 4, "ap_memory", "MemPortDIN2", 1),
};
const char* HLS_Design_Meta::dut_name = "msm_arr";
