onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /sys_test/ap_rst
add wave -noupdate /sys_test/uut/ap_done
add wave -noupdate /sys_test/uut/ap_ready
add wave -noupdate /sys_test/uut/ap_start
add wave -noupdate /sys_test/ap_clk
add wave -noupdate -expand -group GBUFF /sys_test/uut/GBUFF_P_V_U/address0
add wave -noupdate -expand -group GBUFF /sys_test/uut/GBUFF_P_V_U/ce0
add wave -noupdate -expand -group GBUFF /sys_test/uut/GBUFF_P_V_U/we0
add wave -noupdate -expand -group GBUFF /sys_test/uut/GBUFF_P_V_U/d0
add wave -noupdate -expand -group GBUFF /sys_test/uut/GBUFF_P_V_U/q0
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_0_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_0_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_0_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_0_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_0_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_0_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_0_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_0_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_1_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_1_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_1_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_1_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_1_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_1_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_1_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_1_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_2_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_2_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_2_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_2_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_2_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_2_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_2_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_2_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_3_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_3_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_3_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_3_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_3_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_3_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_3_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_3_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_4_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_4_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_4_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_4_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_4_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_4_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_4_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_4_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_5_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_5_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_5_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_5_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_5_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_5_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_5_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_5_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_6_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_6_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_6_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_6_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_6_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_6_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_6_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_6_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_7_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_7_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_7_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_7_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_7_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_7_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_7_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_7_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_8_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_8_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_8_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_8_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_8_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_8_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_8_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_8_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_9_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_9_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_9_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_9_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_9_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_9_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_9_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_9_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_10_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_10_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_10_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_10_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_10_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_10_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_10_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_10_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_11_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_11_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_11_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_11_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_11_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_11_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_11_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_11_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_12_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_12_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_12_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_12_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_12_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_12_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_12_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_12_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_13_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_13_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_13_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_13_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_13_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_13_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_13_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_13_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_14_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_14_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_14_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_14_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_14_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_14_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_14_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_14_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_15_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_15_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_15_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_15_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_15_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_15_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_15_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/B_15_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/OVFIFO_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/OVFIFO_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/OVFIFO_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/OVFIFO_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/OVFIFO_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/OVFIFO_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/OVFIFO_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/OVFIFO_U/if_dout
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/CFIFO_U/if_full_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/CFIFO_U/if_write_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/CFIFO_U/if_write
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/CFIFO_U/if_din
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/CFIFO_U/if_num_data_valid
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/CFIFO_U/if_empty_n
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/CFIFO_U/if_read_ce
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/CFIFO_U/if_read
add wave -noupdate /sys_test/uut/grp_bucket_unit_fu_372/CFIFO_U/if_dout
add wave -noupdate /sys_test/uut/GBUFF_P2D_V_U/address0
add wave -noupdate /sys_test/uut/GBUFF_P2D_V_U/ce0
add wave -noupdate /sys_test/uut/GBUFF_P2D_V_U/d0
add wave -noupdate /sys_test/uut/GBUFF_P2D_V_U/we0
add wave -noupdate /sys_test/uut/GBUFF_P2D_V_U/q0
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {94082 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 311
configure wave -valuecolwidth 82
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {820724 ps}
