// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module msm_arr_bucket_unit_sr (
        BFIFO_1176_dout,
        BFIFO_1176_empty_n,
        BFIFO_1176_read,
        B_i_address0,
        B_i_ce0,
        B_i_d0,
        B_i_q0,
        B_i_we0,
        B_i_address1,
        B_i_ce1,
        B_i_d1,
        B_i_q1,
        B_i_we1,
        num_padd_ops,
        count_B_address0,
        count_B_ce0,
        count_B_d0,
        count_B_q0,
        count_B_we0,
        count_B_address1,
        count_B_ce1,
        count_B_d1,
        count_B_q1,
        count_B_we1,
        ap_clk,
        ap_rst,
        num_padd_ops_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [42:0] BFIFO_1176_dout;
input   BFIFO_1176_empty_n;
output   BFIFO_1176_read;
output  [4:0] B_i_address0;
output   B_i_ce0;
output  [31:0] B_i_d0;
input  [31:0] B_i_q0;
output   B_i_we0;
output  [4:0] B_i_address1;
output   B_i_ce1;
output  [31:0] B_i_d1;
input  [31:0] B_i_q1;
output   B_i_we1;
input  [12:0] num_padd_ops;
output  [3:0] count_B_address0;
output   count_B_ce0;
output  [12:0] count_B_d0;
input  [12:0] count_B_q0;
output   count_B_we0;
output  [3:0] count_B_address1;
output   count_B_ce1;
output  [12:0] count_B_d1;
input  [12:0] count_B_q1;
output   count_B_we1;
input   ap_clk;
input   ap_rst;
input   num_padd_ops_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    bucket_unit_sr_Block_split153_proc7_U0_ap_start;
wire    bucket_unit_sr_Block_split153_proc7_U0_ap_done;
wire    bucket_unit_sr_Block_split153_proc7_U0_ap_continue;
wire    bucket_unit_sr_Block_split153_proc7_U0_ap_idle;
wire    bucket_unit_sr_Block_split153_proc7_U0_ap_ready;
wire    bucket_unit_sr_Block_split153_proc7_U0_start_out;
wire    bucket_unit_sr_Block_split153_proc7_U0_start_write;
wire   [4:0] bucket_unit_sr_Block_split153_proc7_U0_B_i_address0;
wire    bucket_unit_sr_Block_split153_proc7_U0_B_i_ce0;
wire    bucket_unit_sr_Block_split153_proc7_U0_B_i_we0;
wire   [31:0] bucket_unit_sr_Block_split153_proc7_U0_B_i_d0;
wire   [4:0] bucket_unit_sr_Block_split153_proc7_U0_B_i_address1;
wire    bucket_unit_sr_Block_split153_proc7_U0_B_i_ce1;
wire    bucket_unit_sr_Block_split153_proc7_U0_B_i_we1;
wire   [31:0] bucket_unit_sr_Block_split153_proc7_U0_B_i_d1;
wire    bucket_unit_sr_Block_split153_proc7_U0_BFIFO_1176_read;
wire   [3:0] bucket_unit_sr_Block_split153_proc7_U0_count_B_address0;
wire    bucket_unit_sr_Block_split153_proc7_U0_count_B_ce0;
wire    bucket_unit_sr_Block_split153_proc7_U0_BFIFO_2_read;
wire   [81:0] bucket_unit_sr_Block_split153_proc7_U0_CFIFO_din;
wire    bucket_unit_sr_Block_split153_proc7_U0_CFIFO_write;
wire   [12:0] bucket_unit_sr_Block_split153_proc7_U0_num_padd_ops_out_din;
wire    bucket_unit_sr_Block_split153_proc7_U0_num_padd_ops_out_write;
wire    ap_sync_continue;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_start;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_done;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_continue;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_idle;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_ready;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_num_padd_ops_read;
wire   [42:0] bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_BFIFO_2_din;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_BFIFO_2_write;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_CFIFO_read;
wire    BFIFO_2_full_n;
wire   [42:0] BFIFO_2_dout;
wire    BFIFO_2_empty_n;
wire    CFIFO_full_n;
wire   [81:0] CFIFO_dout;
wire    CFIFO_empty_n;
wire    num_padd_ops_c_full_n;
wire   [12:0] num_padd_ops_c_dout;
wire    num_padd_ops_c_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_din;
wire    start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_full_n;
wire   [0:0] start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_dout;
wire    start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_empty_n;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_start_full_n;
wire    bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_start_write;

msm_arr_bucket_unit_sr_Block_split153_proc7 bucket_unit_sr_Block_split153_proc7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(bucket_unit_sr_Block_split153_proc7_U0_ap_start),
    .start_full_n(start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_full_n),
    .ap_done(bucket_unit_sr_Block_split153_proc7_U0_ap_done),
    .ap_continue(bucket_unit_sr_Block_split153_proc7_U0_ap_continue),
    .ap_idle(bucket_unit_sr_Block_split153_proc7_U0_ap_idle),
    .ap_ready(bucket_unit_sr_Block_split153_proc7_U0_ap_ready),
    .start_out(bucket_unit_sr_Block_split153_proc7_U0_start_out),
    .start_write(bucket_unit_sr_Block_split153_proc7_U0_start_write),
    .num_padd_ops(num_padd_ops),
    .B_i_address0(bucket_unit_sr_Block_split153_proc7_U0_B_i_address0),
    .B_i_ce0(bucket_unit_sr_Block_split153_proc7_U0_B_i_ce0),
    .B_i_we0(bucket_unit_sr_Block_split153_proc7_U0_B_i_we0),
    .B_i_d0(bucket_unit_sr_Block_split153_proc7_U0_B_i_d0),
    .B_i_address1(bucket_unit_sr_Block_split153_proc7_U0_B_i_address1),
    .B_i_ce1(bucket_unit_sr_Block_split153_proc7_U0_B_i_ce1),
    .B_i_we1(bucket_unit_sr_Block_split153_proc7_U0_B_i_we1),
    .B_i_d1(bucket_unit_sr_Block_split153_proc7_U0_B_i_d1),
    .BFIFO_1176_dout(BFIFO_1176_dout),
    .BFIFO_1176_empty_n(BFIFO_1176_empty_n),
    .BFIFO_1176_read(bucket_unit_sr_Block_split153_proc7_U0_BFIFO_1176_read),
    .count_B_address0(bucket_unit_sr_Block_split153_proc7_U0_count_B_address0),
    .count_B_ce0(bucket_unit_sr_Block_split153_proc7_U0_count_B_ce0),
    .count_B_q0(count_B_q0),
    .BFIFO_2_dout(BFIFO_2_dout),
    .BFIFO_2_empty_n(BFIFO_2_empty_n),
    .BFIFO_2_read(bucket_unit_sr_Block_split153_proc7_U0_BFIFO_2_read),
    .CFIFO_din(bucket_unit_sr_Block_split153_proc7_U0_CFIFO_din),
    .CFIFO_full_n(CFIFO_full_n),
    .CFIFO_write(bucket_unit_sr_Block_split153_proc7_U0_CFIFO_write),
    .num_padd_ops_out_din(bucket_unit_sr_Block_split153_proc7_U0_num_padd_ops_out_din),
    .num_padd_ops_out_full_n(num_padd_ops_c_full_n),
    .num_padd_ops_out_write(bucket_unit_sr_Block_split153_proc7_U0_num_padd_ops_out_write)
);

msm_arr_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8 bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_start),
    .ap_done(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_done),
    .ap_continue(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_continue),
    .ap_idle(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_idle),
    .ap_ready(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_ready),
    .num_padd_ops_dout(num_padd_ops_c_dout),
    .num_padd_ops_empty_n(num_padd_ops_c_empty_n),
    .num_padd_ops_read(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_num_padd_ops_read),
    .BFIFO_2_din(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_BFIFO_2_din),
    .BFIFO_2_full_n(BFIFO_2_full_n),
    .BFIFO_2_write(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_BFIFO_2_write),
    .CFIFO_dout(CFIFO_dout),
    .CFIFO_empty_n(CFIFO_empty_n),
    .CFIFO_read(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_CFIFO_read)
);

msm_arr_fifo_w43_d15_S BFIFO_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_BFIFO_2_din),
    .if_full_n(BFIFO_2_full_n),
    .if_write(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_BFIFO_2_write),
    .if_dout(BFIFO_2_dout),
    .if_empty_n(BFIFO_2_empty_n),
    .if_read(bucket_unit_sr_Block_split153_proc7_U0_BFIFO_2_read)
);

msm_arr_fifo_w82_d32_A CFIFO_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(bucket_unit_sr_Block_split153_proc7_U0_CFIFO_din),
    .if_full_n(CFIFO_full_n),
    .if_write(bucket_unit_sr_Block_split153_proc7_U0_CFIFO_write),
    .if_dout(CFIFO_dout),
    .if_empty_n(CFIFO_empty_n),
    .if_read(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_CFIFO_read)
);

msm_arr_fifo_w13_d2_S num_padd_ops_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(bucket_unit_sr_Block_split153_proc7_U0_num_padd_ops_out_din),
    .if_full_n(num_padd_ops_c_full_n),
    .if_write(bucket_unit_sr_Block_split153_proc7_U0_num_padd_ops_out_write),
    .if_dout(num_padd_ops_c_dout),
    .if_empty_n(num_padd_ops_c_empty_n),
    .if_read(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_num_padd_ops_read)
);

msm_arr_start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0 start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_din),
    .if_full_n(start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_full_n),
    .if_write(bucket_unit_sr_Block_split153_proc7_U0_start_write),
    .if_dout(start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_dout),
    .if_empty_n(start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_empty_n),
    .if_read(bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_ready)
);

assign BFIFO_1176_read = bucket_unit_sr_Block_split153_proc7_U0_BFIFO_1176_read;

assign B_i_address0 = bucket_unit_sr_Block_split153_proc7_U0_B_i_address0;

assign B_i_address1 = bucket_unit_sr_Block_split153_proc7_U0_B_i_address1;

assign B_i_ce0 = bucket_unit_sr_Block_split153_proc7_U0_B_i_ce0;

assign B_i_ce1 = bucket_unit_sr_Block_split153_proc7_U0_B_i_ce1;

assign B_i_d0 = bucket_unit_sr_Block_split153_proc7_U0_B_i_d0;

assign B_i_d1 = bucket_unit_sr_Block_split153_proc7_U0_B_i_d1;

assign B_i_we0 = bucket_unit_sr_Block_split153_proc7_U0_B_i_we0;

assign B_i_we1 = bucket_unit_sr_Block_split153_proc7_U0_B_i_we1;

assign ap_done = ap_sync_done;

assign ap_idle = (bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_idle & bucket_unit_sr_Block_split153_proc7_U0_ap_idle);

assign ap_ready = bucket_unit_sr_Block_split153_proc7_U0_ap_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_done & bucket_unit_sr_Block_split153_proc7_U0_ap_done);

assign ap_sync_ready = bucket_unit_sr_Block_split153_proc7_U0_ap_ready;

assign bucket_unit_sr_Block_split153_proc7_U0_ap_continue = ap_sync_continue;

assign bucket_unit_sr_Block_split153_proc7_U0_ap_start = ap_start;

assign bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_continue = ap_sync_continue;

assign bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_ap_start = start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_empty_n;

assign bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_start_full_n = 1'b1;

assign bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_start_write = 1'b0;

assign count_B_address0 = bucket_unit_sr_Block_split153_proc7_U0_count_B_address0;

assign count_B_address1 = 4'd0;

assign count_B_ce0 = bucket_unit_sr_Block_split153_proc7_U0_count_B_ce0;

assign count_B_ce1 = 1'b0;

assign count_B_d0 = 13'd0;

assign count_B_d1 = 13'd0;

assign count_B_we0 = 1'b0;

assign count_B_we1 = 1'b0;

assign start_for_bucket_unit_sr_Loop_VITIS_LOOP_327_5_proc8_U0_din = 1'b1;

endmodule //msm_arr_bucket_unit_sr
