// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module msm_arr_pdouble (
        ap_clk,
        ap_rst,
        p_x,
        p_y,
        p_z,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [12:0] p_x;
input  [12:0] p_y;
input  [12:0] p_z;
output  [12:0] ap_return_0;
output  [12:0] ap_return_1;
output  [12:0] ap_return_2;
input   ap_ce;

reg[12:0] ap_return_0;
reg[12:0] ap_return_1;
reg[12:0] ap_return_2;

reg   [12:0] p_x_read_reg_1696;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_pp0_stage0_11001;
reg   [12:0] p_x_read_reg_1696_pp0_iter1_reg;
reg   [12:0] p_x_read_reg_1696_pp0_iter2_reg;
reg   [12:0] p_x_read_reg_1696_pp0_iter3_reg;
reg   [12:0] p_x_read_reg_1696_pp0_iter4_reg;
reg   [12:0] p_x_read_reg_1696_pp0_iter5_reg;
wire   [25:0] zext_ln1345_1_fu_74_p1;
wire   [25:0] zext_ln1345_fu_82_p1;
wire   [25:0] grp_fu_1634_p2;
reg   [25:0] ret_1_reg_1721;
wire   [13:0] t_V_fu_134_p2;
reg   [13:0] t_V_reg_1726;
wire   [12:0] trunc_ln1497_20_fu_140_p1;
reg   [12:0] trunc_ln1497_20_reg_1732;
wire   [25:0] grp_fu_1643_p2;
reg   [25:0] ret_14_reg_1737;
wire   [13:0] t_V_5_fu_193_p2;
reg   [13:0] t_V_5_reg_1742;
wire   [12:0] trunc_ln1497_25_fu_199_p1;
reg   [12:0] trunc_ln1497_25_reg_1748;
wire   [25:0] y_V_7_fu_253_p3;
reg   [25:0] y_V_7_reg_1753;
wire   [25:0] y_V_45_fu_311_p3;
reg   [25:0] y_V_45_reg_1760;
wire   [25:0] grp_fu_1652_p2;
reg   [25:0] ret_reg_1767;
wire   [13:0] t_fu_368_p2;
reg   [13:0] t_reg_1772;
wire   [12:0] trunc_ln1497_fu_374_p1;
reg   [12:0] trunc_ln1497_reg_1778;
wire   [12:0] y_V_49_fu_411_p3;
reg   [12:0] y_V_49_reg_1783;
reg   [12:0] y_V_49_reg_1783_pp0_iter6_reg;
wire   [12:0] select_ln26_fu_452_p3;
reg   [12:0] select_ln26_reg_1790;
reg   [12:0] select_ln26_reg_1790_pp0_iter6_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter7_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter8_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter9_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter10_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter11_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter12_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter13_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter14_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter15_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter16_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter17_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter18_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter19_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter20_reg;
reg   [12:0] select_ln26_reg_1790_pp0_iter21_reg;
wire   [25:0] y_V_2_fu_510_p3;
reg   [25:0] y_V_2_reg_1796;
wire   [12:0] y_V_50_fu_548_p2;
reg   [12:0] y_V_50_reg_1803;
wire   [12:0] y_V_51_fu_587_p3;
reg   [12:0] y_V_51_reg_1808;
reg   [12:0] y_V_51_reg_1808_pp0_iter8_reg;
reg   [12:0] y_V_51_reg_1808_pp0_iter9_reg;
reg   [12:0] y_V_51_reg_1808_pp0_iter10_reg;
reg   [12:0] y_V_51_reg_1808_pp0_iter11_reg;
reg   [12:0] y_V_51_reg_1808_pp0_iter12_reg;
wire   [25:0] zext_ln1345_2_fu_595_p1;
wire   [25:0] zext_ln1345_3_fu_598_p1;
wire   [12:0] x_V_5_fu_630_p2;
reg   [12:0] x_V_5_reg_1830;
wire   [0:0] icmp_ln878_3_fu_646_p2;
reg   [0:0] icmp_ln878_3_reg_1835;
wire   [25:0] zext_ln1345_4_fu_669_p1;
reg   [25:0] zext_ln1345_4_reg_1840;
reg   [25:0] zext_ln1345_4_reg_1840_pp0_iter10_reg;
reg   [25:0] zext_ln1345_4_reg_1840_pp0_iter11_reg;
reg   [25:0] zext_ln1345_4_reg_1840_pp0_iter12_reg;
reg   [25:0] zext_ln1345_4_reg_1840_pp0_iter13_reg;
reg   [25:0] zext_ln1345_4_reg_1840_pp0_iter14_reg;
reg   [25:0] zext_ln1345_4_reg_1840_pp0_iter15_reg;
wire   [25:0] grp_fu_1661_p2;
reg   [25:0] ret_2_reg_1847;
wire   [13:0] t_V_1_fu_722_p2;
reg   [13:0] t_V_1_reg_1852;
wire   [12:0] trunc_ln1497_21_fu_728_p1;
reg   [12:0] trunc_ln1497_21_reg_1858;
wire   [25:0] grp_fu_1670_p2;
reg   [25:0] ret_4_reg_1863;
wire   [13:0] t_V_2_fu_781_p2;
reg   [13:0] t_V_2_reg_1868;
wire   [12:0] trunc_ln1497_22_fu_787_p1;
reg   [12:0] trunc_ln1497_22_reg_1874;
wire   [25:0] y_V_13_fu_841_p3;
reg   [25:0] y_V_13_reg_1879;
wire   [25:0] y_V_20_fu_899_p3;
reg   [25:0] y_V_20_reg_1886;
wire   [12:0] y_V_52_fu_940_p3;
reg   [12:0] y_V_52_reg_1893;
reg   [12:0] y_V_52_reg_1893_pp0_iter13_reg;
reg   [12:0] y_V_52_reg_1893_pp0_iter14_reg;
reg   [12:0] y_V_52_reg_1893_pp0_iter15_reg;
reg   [12:0] y_V_52_reg_1893_pp0_iter16_reg;
reg   [12:0] y_V_52_reg_1893_pp0_iter17_reg;
reg   [12:0] y_V_52_reg_1893_pp0_iter18_reg;
reg   [12:0] y_V_52_reg_1893_pp0_iter19_reg;
wire   [12:0] x_V_1_fu_981_p3;
reg   [12:0] x_V_1_reg_1901;
wire   [25:0] grp_fu_1679_p2;
reg   [25:0] ret_8_reg_1907;
wire   [13:0] t_V_3_fu_1038_p2;
reg   [13:0] t_V_3_reg_1912;
wire   [12:0] trunc_ln1497_23_fu_1044_p1;
reg   [12:0] trunc_ln1497_23_reg_1918;
wire   [12:0] x_V_2_fu_1064_p2;
reg   [12:0] x_V_2_reg_1923;
wire   [12:0] select_ln213_2_fu_1075_p3;
reg   [12:0] select_ln213_2_reg_1928;
wire   [25:0] y_V_29_fu_1133_p3;
reg   [25:0] y_V_29_reg_1933;
wire   [12:0] y_V_55_fu_1178_p2;
reg   [12:0] y_V_55_reg_1940;
reg   [12:0] y_V_55_reg_1940_pp0_iter15_reg;
wire   [12:0] x_V_8_fu_1217_p3;
reg   [12:0] x_V_8_reg_1947;
wire   [0:0] icmp_ln878_4_fu_1233_p2;
reg   [0:0] icmp_ln878_4_reg_1953;
wire   [12:0] y_V_56_fu_1275_p2;
reg   [12:0] y_V_56_reg_1958;
reg   [12:0] y_V_56_reg_1958_pp0_iter16_reg;
reg   [12:0] y_V_56_reg_1958_pp0_iter17_reg;
reg   [12:0] y_V_56_reg_1958_pp0_iter18_reg;
reg   [12:0] y_V_56_reg_1958_pp0_iter19_reg;
reg   [12:0] y_V_56_reg_1958_pp0_iter20_reg;
reg   [12:0] y_V_56_reg_1958_pp0_iter21_reg;
wire   [25:0] grp_fu_1688_p2;
reg   [25:0] ret_13_reg_1970;
wire   [13:0] t_V_4_fu_1356_p2;
reg   [13:0] t_V_4_reg_1975;
wire   [12:0] trunc_ln1497_24_fu_1362_p1;
reg   [12:0] trunc_ln1497_24_reg_1981;
wire   [12:0] y_V_57_fu_1392_p2;
reg   [12:0] y_V_57_reg_1986;
wire   [25:0] y_V_40_fu_1448_p3;
reg   [25:0] y_V_40_reg_1992;
wire   [12:0] y_V_48_fu_1516_p2;
reg   [12:0] y_V_48_reg_1999;
wire   [12:0] x_V_12_fu_1555_p3;
reg   [12:0] x_V_12_reg_2005;
wire    ap_block_pp0_stage0;
wire   [12:0] trunc_ln1497_3_fu_85_p4;
wire   [8:0] trunc_ln1497_4_fu_98_p4;
wire   [4:0] trunc_ln1497_5_fu_111_p4;
wire   [9:0] zext_ln1497_5_fu_107_p1;
wire   [9:0] zext_ln1497_6_fu_120_p1;
wire   [9:0] add_ln208_2_fu_124_p2;
wire   [13:0] zext_ln208_1_fu_130_p1;
wire   [13:0] zext_ln1497_4_fu_94_p1;
wire   [12:0] trunc_ln1497_17_fu_144_p4;
wire   [8:0] trunc_ln1497_18_fu_157_p4;
wire   [4:0] trunc_ln1497_19_fu_170_p4;
wire   [9:0] zext_ln1497_25_fu_166_p1;
wire   [9:0] zext_ln1497_26_fu_179_p1;
wire   [9:0] add_ln208_12_fu_183_p2;
wire   [13:0] zext_ln208_6_fu_189_p1;
wire   [13:0] zext_ln1497_24_fu_153_p1;
wire   [22:0] r_3_fu_213_p3;
wire   [25:0] zext_ln21_1_fu_203_p1;
(* use_dsp48 = "no" *) wire   [25:0] sub_ln213_3_fu_224_p2;
wire   [25:0] zext_ln1497_7_fu_220_p1;
wire   [25:0] add_ln213_3_fu_229_p2;
wire   [25:0] r_2_fu_206_p3;
wire   [25:0] y_V_5_fu_235_p2;
wire   [0:0] icmp_ln882_3_fu_241_p2;
wire   [25:0] y_V_6_fu_247_p2;
wire   [22:0] r_13_fu_271_p3;
wire   [25:0] zext_ln21_6_fu_261_p1;
(* use_dsp48 = "no" *) wire   [25:0] sub_ln213_24_fu_282_p2;
wire   [25:0] zext_ln1497_27_fu_278_p1;
wire   [25:0] add_ln213_24_fu_287_p2;
wire   [25:0] r_12_fu_264_p3;
wire   [25:0] y_V_43_fu_293_p2;
wire   [0:0] icmp_ln882_18_fu_299_p2;
wire   [25:0] y_V_44_fu_305_p2;
wire   [12:0] trunc_ln_fu_319_p4;
wire   [8:0] trunc_ln1497_1_fu_332_p4;
wire   [4:0] trunc_ln1497_2_fu_345_p4;
wire   [9:0] zext_ln1497_1_fu_341_p1;
wire   [9:0] zext_ln1497_2_fu_354_p1;
wire   [9:0] add_ln208_fu_358_p2;
wire   [13:0] zext_ln208_fu_364_p1;
wire   [13:0] zext_ln1497_fu_328_p1;
wire   [0:0] icmp_ln882_4_fu_378_p2;
wire   [25:0] y_V_8_fu_383_p2;
wire   [25:0] y_V_9_fu_388_p3;
wire   [12:0] trunc_ln213_1_fu_401_p1;
wire   [0:0] icmp_ln882_5_fu_395_p2;
wire   [12:0] add_ln26_1_fu_405_p2;
wire   [0:0] icmp_ln882_19_fu_419_p2;
wire   [25:0] y_V_46_fu_424_p2;
wire   [25:0] y_V_47_fu_429_p3;
wire   [12:0] trunc_ln213_6_fu_442_p1;
wire   [0:0] icmp_ln882_20_fu_436_p2;
wire   [12:0] add_ln26_6_fu_446_p2;
wire   [22:0] r_1_fu_470_p3;
wire   [25:0] zext_ln21_fu_460_p1;
(* use_dsp48 = "no" *) wire   [25:0] sub_ln213_1_fu_481_p2;
wire   [25:0] zext_ln1497_3_fu_477_p1;
wire   [25:0] add_ln213_fu_486_p2;
wire   [25:0] r_fu_463_p3;
wire   [25:0] y_V_fu_492_p2;
wire   [0:0] icmp_ln882_fu_498_p2;
wire   [25:0] y_V_1_fu_504_p2;
wire   [13:0] zext_ln215_1_fu_521_p1;
wire   [13:0] zext_ln215_fu_518_p1;
wire   [13:0] ret_3_fu_524_p2;
wire   [0:0] icmp_ln878_fu_530_p2;
wire   [12:0] add_ln213_9_fu_536_p2;
wire   [12:0] select_ln213_fu_540_p3;
wire   [0:0] icmp_ln882_1_fu_554_p2;
wire   [25:0] y_V_3_fu_559_p2;
wire   [25:0] y_V_4_fu_564_p3;
wire   [12:0] trunc_ln213_fu_577_p1;
wire   [0:0] icmp_ln882_2_fu_571_p2;
wire   [12:0] add_ln26_fu_581_p2;
wire   [13:0] ret_6_fu_604_p3;
wire   [0:0] icmp_ln878_2_fu_611_p2;
wire   [12:0] shl_ln213_1_fu_617_p2;
wire   [12:0] select_ln213_4_fu_622_p3;
wire   [13:0] zext_ln1346_1_fu_636_p1;
wire   [13:0] zext_ln1346_fu_601_p1;
wire   [13:0] ret_7_fu_640_p2;
wire   [12:0] add_ln213_15_fu_652_p2;
wire   [12:0] select_ln213_5_fu_656_p3;
wire   [12:0] y_V_54_fu_663_p2;
wire   [12:0] trunc_ln1497_6_fu_673_p4;
wire   [8:0] trunc_ln1497_7_fu_686_p4;
wire   [4:0] trunc_ln1497_8_fu_699_p4;
wire   [9:0] zext_ln1497_9_fu_695_p1;
wire   [9:0] zext_ln1497_10_fu_708_p1;
wire   [9:0] add_ln208_4_fu_712_p2;
wire   [13:0] zext_ln208_2_fu_718_p1;
wire   [13:0] zext_ln1497_8_fu_682_p1;
wire   [12:0] trunc_ln1497_9_fu_732_p4;
wire   [8:0] trunc_ln1497_s_fu_745_p4;
wire   [4:0] trunc_ln1497_10_fu_758_p4;
wire   [9:0] zext_ln1497_13_fu_754_p1;
wire   [9:0] zext_ln1497_14_fu_767_p1;
wire   [9:0] add_ln208_6_fu_771_p2;
wire   [13:0] zext_ln208_3_fu_777_p1;
wire   [13:0] zext_ln1497_12_fu_741_p1;
wire   [22:0] r_5_fu_801_p3;
wire   [25:0] zext_ln21_2_fu_791_p1;
(* use_dsp48 = "no" *) wire   [25:0] sub_ln213_6_fu_812_p2;
wire   [25:0] zext_ln1497_11_fu_808_p1;
wire   [25:0] add_ln213_6_fu_817_p2;
wire   [25:0] r_4_fu_794_p3;
wire   [25:0] y_V_11_fu_823_p2;
wire   [0:0] icmp_ln882_6_fu_829_p2;
wire   [25:0] y_V_12_fu_835_p2;
wire   [22:0] r_7_fu_859_p3;
wire   [25:0] zext_ln21_3_fu_849_p1;
(* use_dsp48 = "no" *) wire   [25:0] sub_ln213_9_fu_870_p2;
wire   [25:0] zext_ln1497_15_fu_866_p1;
wire   [25:0] add_ln213_10_fu_875_p2;
wire   [25:0] r_6_fu_852_p3;
wire   [25:0] y_V_18_fu_881_p2;
wire   [0:0] icmp_ln882_9_fu_887_p2;
wire   [25:0] y_V_19_fu_893_p2;
wire   [0:0] icmp_ln882_7_fu_907_p2;
wire   [25:0] y_V_14_fu_912_p2;
wire   [25:0] y_V_15_fu_917_p3;
wire   [12:0] trunc_ln213_2_fu_930_p1;
wire   [0:0] icmp_ln882_8_fu_924_p2;
wire   [12:0] add_ln26_2_fu_934_p2;
wire   [0:0] icmp_ln882_10_fu_948_p2;
wire   [25:0] y_V_21_fu_953_p2;
wire   [25:0] y_V_22_fu_958_p3;
wire   [12:0] trunc_ln213_3_fu_971_p1;
wire   [0:0] icmp_ln882_11_fu_965_p2;
wire   [12:0] add_ln26_3_fu_975_p2;
wire   [12:0] trunc_ln1497_11_fu_989_p4;
wire   [8:0] trunc_ln1497_12_fu_1002_p4;
wire   [4:0] trunc_ln1497_13_fu_1015_p4;
wire   [9:0] zext_ln1497_17_fu_1011_p1;
wire   [9:0] zext_ln1497_18_fu_1024_p1;
wire   [9:0] add_ln208_8_fu_1028_p2;
wire   [13:0] zext_ln208_4_fu_1034_p1;
wire   [13:0] zext_ln1497_16_fu_998_p1;
wire   [0:0] icmp_ln886_fu_1048_p2;
wire   [12:0] select_ln213_1_fu_1052_p3;
wire   [12:0] sub_ln213_fu_1060_p2;
wire   [0:0] icmp_ln886_1_fu_1070_p2;
wire   [22:0] r_9_fu_1093_p3;
wire   [25:0] zext_ln21_4_fu_1083_p1;
(* use_dsp48 = "no" *) wire   [25:0] sub_ln213_15_fu_1104_p2;
wire   [25:0] zext_ln1497_19_fu_1100_p1;
wire   [25:0] add_ln213_16_fu_1109_p2;
wire   [25:0] r_8_fu_1086_p3;
wire   [25:0] y_V_27_fu_1115_p2;
wire   [0:0] icmp_ln882_12_fu_1121_p2;
wire   [25:0] y_V_28_fu_1127_p2;
wire   [12:0] sub_ln213_11_fu_1141_p2;
wire   [12:0] y_V_53_fu_1145_p2;
wire   [13:0] ret_5_fu_1150_p3;
wire   [0:0] icmp_ln878_1_fu_1158_p2;
wire   [12:0] shl_ln213_fu_1164_p2;
wire   [12:0] select_ln213_3_fu_1170_p3;
wire   [0:0] icmp_ln882_13_fu_1184_p2;
wire   [25:0] y_V_30_fu_1189_p2;
wire   [25:0] y_V_31_fu_1194_p3;
wire   [12:0] trunc_ln213_4_fu_1207_p1;
wire   [0:0] icmp_ln882_14_fu_1201_p2;
wire   [12:0] add_ln26_4_fu_1211_p2;
wire   [13:0] ret_9_fu_1225_p3;
wire   [12:0] shl_ln213_2_fu_1239_p2;
wire   [12:0] select_ln213_6_fu_1244_p3;
wire   [12:0] y_V_33_fu_1251_p2;
wire   [0:0] icmp_ln886_2_fu_1257_p2;
wire   [12:0] select_ln213_7_fu_1262_p3;
wire   [12:0] sub_ln213_5_fu_1270_p2;
wire   [0:0] icmp_ln886_3_fu_1281_p2;
wire   [12:0] sub_ln213_18_fu_1293_p2;
wire   [12:0] select_ln213_8_fu_1285_p3;
wire   [12:0] y_V_37_fu_1297_p2;
wire   [12:0] trunc_ln1497_14_fu_1307_p4;
wire   [8:0] trunc_ln1497_15_fu_1320_p4;
wire   [4:0] trunc_ln1497_16_fu_1333_p4;
wire   [9:0] zext_ln1497_21_fu_1329_p1;
wire   [9:0] zext_ln1497_22_fu_1342_p1;
wire   [9:0] add_ln208_10_fu_1346_p2;
wire   [13:0] zext_ln208_5_fu_1352_p1;
wire   [13:0] zext_ln1497_20_fu_1316_p1;
wire   [13:0] ret_10_fu_1366_p3;
wire   [0:0] icmp_ln878_5_fu_1373_p2;
wire   [12:0] shl_ln213_3_fu_1379_p2;
wire   [12:0] select_ln213_9_fu_1384_p3;
wire   [22:0] r_11_fu_1408_p3;
wire   [25:0] zext_ln21_5_fu_1398_p1;
(* use_dsp48 = "no" *) wire   [25:0] sub_ln213_22_fu_1419_p2;
wire   [25:0] zext_ln1497_23_fu_1415_p1;
wire   [25:0] add_ln213_21_fu_1424_p2;
wire   [25:0] r_10_fu_1401_p3;
wire   [25:0] y_V_38_fu_1430_p2;
wire   [0:0] icmp_ln882_15_fu_1436_p2;
wire   [25:0] y_V_39_fu_1442_p2;
wire   [13:0] ret_11_fu_1456_p3;
wire   [0:0] icmp_ln878_6_fu_1463_p2;
wire   [12:0] shl_ln213_4_fu_1469_p2;
wire   [12:0] select_ln213_10_fu_1474_p3;
wire   [12:0] y_V_58_fu_1482_p2;
wire   [13:0] ret_12_fu_1488_p3;
wire   [0:0] icmp_ln878_7_fu_1496_p2;
wire   [12:0] shl_ln213_5_fu_1502_p2;
wire   [12:0] select_ln213_11_fu_1508_p3;
wire   [0:0] icmp_ln882_16_fu_1522_p2;
wire   [25:0] y_V_41_fu_1527_p2;
wire   [25:0] y_V_42_fu_1532_p3;
wire   [12:0] trunc_ln213_5_fu_1545_p1;
wire   [0:0] icmp_ln882_17_fu_1539_p2;
wire   [12:0] add_ln26_5_fu_1549_p2;
wire   [0:0] icmp_ln886_4_fu_1563_p2;
wire   [12:0] sub_ln213_26_fu_1575_p2;
wire   [12:0] select_ln213_12_fu_1567_p3;
wire   [13:0] ret_15_fu_1585_p3;
wire   [0:0] icmp_ln878_8_fu_1592_p2;
wire   [12:0] shl_ln213_6_fu_1598_p2;
wire   [12:0] select_ln213_13_fu_1603_p3;
wire   [12:0] b_V_fu_1579_p2;
wire   [12:0] c_V_fu_1611_p2;
wire   [12:0] grp_fu_1634_p0;
wire   [12:0] grp_fu_1634_p1;
wire   [12:0] grp_fu_1643_p0;
wire   [12:0] grp_fu_1643_p1;
wire   [12:0] grp_fu_1652_p0;
wire   [12:0] grp_fu_1652_p1;
wire   [12:0] grp_fu_1661_p0;
wire   [12:0] grp_fu_1661_p1;
wire   [12:0] grp_fu_1670_p0;
wire   [12:0] grp_fu_1670_p1;
wire   [12:0] grp_fu_1679_p0;
wire   [12:0] grp_fu_1679_p1;
wire   [12:0] grp_fu_1688_p0;
wire   [12:0] grp_fu_1688_p1;
reg    grp_fu_1634_ce;
reg    grp_fu_1643_ce;
reg    grp_fu_1652_ce;
reg    grp_fu_1661_ce;
reg    grp_fu_1670_ce;
reg    grp_fu_1679_ce;
reg    grp_fu_1688_ce;
reg    ap_ce_reg;
reg   [12:0] p_x_int_reg;
reg   [12:0] p_y_int_reg;
reg   [12:0] p_z_int_reg;
reg   [12:0] ap_return_0_int_reg;
reg   [12:0] ap_return_1_int_reg;
reg   [12:0] ap_return_2_int_reg;
wire   [25:0] grp_fu_1643_p00;
wire   [25:0] grp_fu_1688_p00;

msm_arr_mul_mul_13ns_13ns_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_mul_13ns_13ns_26_4_0_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1634_p0),
    .din1(grp_fu_1634_p1),
    .ce(grp_fu_1634_ce),
    .dout(grp_fu_1634_p2)
);

msm_arr_mul_mul_13ns_13ns_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_mul_13ns_13ns_26_4_0_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1643_p0),
    .din1(grp_fu_1643_p1),
    .ce(grp_fu_1643_ce),
    .dout(grp_fu_1643_p2)
);

msm_arr_mul_mul_13ns_13ns_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_mul_13ns_13ns_26_4_0_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1652_p0),
    .din1(grp_fu_1652_p1),
    .ce(grp_fu_1652_ce),
    .dout(grp_fu_1652_p2)
);

msm_arr_mul_mul_13ns_13ns_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_mul_13ns_13ns_26_4_0_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1661_p0),
    .din1(grp_fu_1661_p1),
    .ce(grp_fu_1661_ce),
    .dout(grp_fu_1661_p2)
);

msm_arr_mul_mul_13ns_13ns_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_mul_13ns_13ns_26_4_0_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1670_p0),
    .din1(grp_fu_1670_p1),
    .ce(grp_fu_1670_ce),
    .dout(grp_fu_1670_p2)
);

msm_arr_mul_mul_13ns_13ns_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_mul_13ns_13ns_26_4_0_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1679_p0),
    .din1(grp_fu_1679_p1),
    .ce(grp_fu_1679_ce),
    .dout(grp_fu_1679_p2)
);

msm_arr_mul_mul_13ns_13ns_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_mul_13ns_13ns_26_4_0_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1688_p0),
    .din1(grp_fu_1688_p1),
    .ce(grp_fu_1688_ce),
    .dout(grp_fu_1688_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= y_V_56_reg_1958_pp0_iter21_reg;
        ap_return_1_int_reg <= b_V_fu_1579_p2;
        ap_return_2_int_reg <= c_V_fu_1611_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        icmp_ln878_3_reg_1835 <= icmp_ln878_3_fu_646_p2;
        icmp_ln878_4_reg_1953 <= icmp_ln878_4_fu_1233_p2;
        p_x_read_reg_1696 <= p_x_int_reg;
        p_x_read_reg_1696_pp0_iter1_reg <= p_x_read_reg_1696;
        p_x_read_reg_1696_pp0_iter2_reg <= p_x_read_reg_1696_pp0_iter1_reg;
        p_x_read_reg_1696_pp0_iter3_reg <= p_x_read_reg_1696_pp0_iter2_reg;
        p_x_read_reg_1696_pp0_iter4_reg <= p_x_read_reg_1696_pp0_iter3_reg;
        p_x_read_reg_1696_pp0_iter5_reg <= p_x_read_reg_1696_pp0_iter4_reg;
        ret_13_reg_1970 <= grp_fu_1688_p2;
        ret_14_reg_1737 <= grp_fu_1643_p2;
        ret_1_reg_1721 <= grp_fu_1634_p2;
        ret_2_reg_1847 <= grp_fu_1661_p2;
        ret_4_reg_1863 <= grp_fu_1670_p2;
        ret_8_reg_1907 <= grp_fu_1679_p2;
        ret_reg_1767 <= grp_fu_1652_p2;
        select_ln213_2_reg_1928[0] <= select_ln213_2_fu_1075_p3[0];
select_ln213_2_reg_1928[12 : 9] <= select_ln213_2_fu_1075_p3[12 : 9];
        select_ln26_reg_1790 <= select_ln26_fu_452_p3;
        select_ln26_reg_1790_pp0_iter10_reg <= select_ln26_reg_1790_pp0_iter9_reg;
        select_ln26_reg_1790_pp0_iter11_reg <= select_ln26_reg_1790_pp0_iter10_reg;
        select_ln26_reg_1790_pp0_iter12_reg <= select_ln26_reg_1790_pp0_iter11_reg;
        select_ln26_reg_1790_pp0_iter13_reg <= select_ln26_reg_1790_pp0_iter12_reg;
        select_ln26_reg_1790_pp0_iter14_reg <= select_ln26_reg_1790_pp0_iter13_reg;
        select_ln26_reg_1790_pp0_iter15_reg <= select_ln26_reg_1790_pp0_iter14_reg;
        select_ln26_reg_1790_pp0_iter16_reg <= select_ln26_reg_1790_pp0_iter15_reg;
        select_ln26_reg_1790_pp0_iter17_reg <= select_ln26_reg_1790_pp0_iter16_reg;
        select_ln26_reg_1790_pp0_iter18_reg <= select_ln26_reg_1790_pp0_iter17_reg;
        select_ln26_reg_1790_pp0_iter19_reg <= select_ln26_reg_1790_pp0_iter18_reg;
        select_ln26_reg_1790_pp0_iter20_reg <= select_ln26_reg_1790_pp0_iter19_reg;
        select_ln26_reg_1790_pp0_iter21_reg <= select_ln26_reg_1790_pp0_iter20_reg;
        select_ln26_reg_1790_pp0_iter6_reg <= select_ln26_reg_1790;
        select_ln26_reg_1790_pp0_iter7_reg <= select_ln26_reg_1790_pp0_iter6_reg;
        select_ln26_reg_1790_pp0_iter8_reg <= select_ln26_reg_1790_pp0_iter7_reg;
        select_ln26_reg_1790_pp0_iter9_reg <= select_ln26_reg_1790_pp0_iter8_reg;
        t_V_1_reg_1852 <= t_V_1_fu_722_p2;
        t_V_2_reg_1868 <= t_V_2_fu_781_p2;
        t_V_3_reg_1912 <= t_V_3_fu_1038_p2;
        t_V_4_reg_1975 <= t_V_4_fu_1356_p2;
        t_V_5_reg_1742 <= t_V_5_fu_193_p2;
        t_V_reg_1726 <= t_V_fu_134_p2;
        t_reg_1772 <= t_fu_368_p2;
        trunc_ln1497_20_reg_1732 <= trunc_ln1497_20_fu_140_p1;
        trunc_ln1497_21_reg_1858 <= trunc_ln1497_21_fu_728_p1;
        trunc_ln1497_22_reg_1874 <= trunc_ln1497_22_fu_787_p1;
        trunc_ln1497_23_reg_1918 <= trunc_ln1497_23_fu_1044_p1;
        trunc_ln1497_24_reg_1981 <= trunc_ln1497_24_fu_1362_p1;
        trunc_ln1497_25_reg_1748 <= trunc_ln1497_25_fu_199_p1;
        trunc_ln1497_reg_1778 <= trunc_ln1497_fu_374_p1;
        x_V_12_reg_2005 <= x_V_12_fu_1555_p3;
        x_V_1_reg_1901 <= x_V_1_fu_981_p3;
        x_V_2_reg_1923 <= x_V_2_fu_1064_p2;
        x_V_5_reg_1830 <= x_V_5_fu_630_p2;
        x_V_8_reg_1947 <= x_V_8_fu_1217_p3;
        y_V_13_reg_1879 <= y_V_13_fu_841_p3;
        y_V_20_reg_1886 <= y_V_20_fu_899_p3;
        y_V_29_reg_1933 <= y_V_29_fu_1133_p3;
        y_V_2_reg_1796 <= y_V_2_fu_510_p3;
        y_V_40_reg_1992 <= y_V_40_fu_1448_p3;
        y_V_45_reg_1760 <= y_V_45_fu_311_p3;
        y_V_48_reg_1999 <= y_V_48_fu_1516_p2;
        y_V_49_reg_1783 <= y_V_49_fu_411_p3;
        y_V_49_reg_1783_pp0_iter6_reg <= y_V_49_reg_1783;
        y_V_50_reg_1803 <= y_V_50_fu_548_p2;
        y_V_51_reg_1808 <= y_V_51_fu_587_p3;
        y_V_51_reg_1808_pp0_iter10_reg <= y_V_51_reg_1808_pp0_iter9_reg;
        y_V_51_reg_1808_pp0_iter11_reg <= y_V_51_reg_1808_pp0_iter10_reg;
        y_V_51_reg_1808_pp0_iter12_reg <= y_V_51_reg_1808_pp0_iter11_reg;
        y_V_51_reg_1808_pp0_iter8_reg <= y_V_51_reg_1808;
        y_V_51_reg_1808_pp0_iter9_reg <= y_V_51_reg_1808_pp0_iter8_reg;
        y_V_52_reg_1893 <= y_V_52_fu_940_p3;
        y_V_52_reg_1893_pp0_iter13_reg <= y_V_52_reg_1893;
        y_V_52_reg_1893_pp0_iter14_reg <= y_V_52_reg_1893_pp0_iter13_reg;
        y_V_52_reg_1893_pp0_iter15_reg <= y_V_52_reg_1893_pp0_iter14_reg;
        y_V_52_reg_1893_pp0_iter16_reg <= y_V_52_reg_1893_pp0_iter15_reg;
        y_V_52_reg_1893_pp0_iter17_reg <= y_V_52_reg_1893_pp0_iter16_reg;
        y_V_52_reg_1893_pp0_iter18_reg <= y_V_52_reg_1893_pp0_iter17_reg;
        y_V_52_reg_1893_pp0_iter19_reg <= y_V_52_reg_1893_pp0_iter18_reg;
        y_V_55_reg_1940 <= y_V_55_fu_1178_p2;
        y_V_55_reg_1940_pp0_iter15_reg <= y_V_55_reg_1940;
        y_V_56_reg_1958 <= y_V_56_fu_1275_p2;
        y_V_56_reg_1958_pp0_iter16_reg <= y_V_56_reg_1958;
        y_V_56_reg_1958_pp0_iter17_reg <= y_V_56_reg_1958_pp0_iter16_reg;
        y_V_56_reg_1958_pp0_iter18_reg <= y_V_56_reg_1958_pp0_iter17_reg;
        y_V_56_reg_1958_pp0_iter19_reg <= y_V_56_reg_1958_pp0_iter18_reg;
        y_V_56_reg_1958_pp0_iter20_reg <= y_V_56_reg_1958_pp0_iter19_reg;
        y_V_56_reg_1958_pp0_iter21_reg <= y_V_56_reg_1958_pp0_iter20_reg;
        y_V_57_reg_1986 <= y_V_57_fu_1392_p2;
        y_V_7_reg_1753 <= y_V_7_fu_253_p3;
        zext_ln1345_4_reg_1840[12 : 0] <= zext_ln1345_4_fu_669_p1[12 : 0];
        zext_ln1345_4_reg_1840_pp0_iter10_reg[12 : 0] <= zext_ln1345_4_reg_1840[12 : 0];
        zext_ln1345_4_reg_1840_pp0_iter11_reg[12 : 0] <= zext_ln1345_4_reg_1840_pp0_iter10_reg[12 : 0];
        zext_ln1345_4_reg_1840_pp0_iter12_reg[12 : 0] <= zext_ln1345_4_reg_1840_pp0_iter11_reg[12 : 0];
        zext_ln1345_4_reg_1840_pp0_iter13_reg[12 : 0] <= zext_ln1345_4_reg_1840_pp0_iter12_reg[12 : 0];
        zext_ln1345_4_reg_1840_pp0_iter14_reg[12 : 0] <= zext_ln1345_4_reg_1840_pp0_iter13_reg[12 : 0];
        zext_ln1345_4_reg_1840_pp0_iter15_reg[12 : 0] <= zext_ln1345_4_reg_1840_pp0_iter14_reg[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_x_int_reg <= p_x;
        p_y_int_reg <= p_y;
        p_z_int_reg <= p_z;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = y_V_56_reg_1958_pp0_iter21_reg;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = b_V_fu_1579_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = c_V_fu_1611_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1634_ce = 1'b1;
    end else begin
        grp_fu_1634_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1643_ce = 1'b1;
    end else begin
        grp_fu_1643_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1652_ce = 1'b1;
    end else begin
        grp_fu_1652_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1661_ce = 1'b1;
    end else begin
        grp_fu_1661_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1670_ce = 1'b1;
    end else begin
        grp_fu_1670_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1679_ce = 1'b1;
    end else begin
        grp_fu_1679_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1688_ce = 1'b1;
    end else begin
        grp_fu_1688_ce = 1'b0;
    end
end

assign add_ln208_10_fu_1346_p2 = (zext_ln1497_21_fu_1329_p1 + zext_ln1497_22_fu_1342_p1);

assign add_ln208_12_fu_183_p2 = (zext_ln1497_25_fu_166_p1 + zext_ln1497_26_fu_179_p1);

assign add_ln208_2_fu_124_p2 = (zext_ln1497_5_fu_107_p1 + zext_ln1497_6_fu_120_p1);

assign add_ln208_4_fu_712_p2 = (zext_ln1497_9_fu_695_p1 + zext_ln1497_10_fu_708_p1);

assign add_ln208_6_fu_771_p2 = (zext_ln1497_13_fu_754_p1 + zext_ln1497_14_fu_767_p1);

assign add_ln208_8_fu_1028_p2 = (zext_ln1497_17_fu_1011_p1 + zext_ln1497_18_fu_1024_p1);

assign add_ln208_fu_358_p2 = (zext_ln1497_1_fu_341_p1 + zext_ln1497_2_fu_354_p1);

assign add_ln213_10_fu_875_p2 = (sub_ln213_9_fu_870_p2 + zext_ln1497_15_fu_866_p1);

assign add_ln213_15_fu_652_p2 = (x_V_5_reg_1830 + y_V_51_reg_1808_pp0_iter8_reg);

assign add_ln213_16_fu_1109_p2 = (sub_ln213_15_fu_1104_p2 + zext_ln1497_19_fu_1100_p1);

assign add_ln213_21_fu_1424_p2 = (sub_ln213_22_fu_1419_p2 + zext_ln1497_23_fu_1415_p1);

assign add_ln213_24_fu_287_p2 = (sub_ln213_24_fu_282_p2 + zext_ln1497_27_fu_278_p1);

assign add_ln213_3_fu_229_p2 = (sub_ln213_3_fu_224_p2 + zext_ln1497_7_fu_220_p1);

assign add_ln213_6_fu_817_p2 = (sub_ln213_6_fu_812_p2 + zext_ln1497_11_fu_808_p1);

assign add_ln213_9_fu_536_p2 = (y_V_49_reg_1783 + p_x_read_reg_1696_pp0_iter5_reg);

assign add_ln213_fu_486_p2 = (sub_ln213_1_fu_481_p2 + zext_ln1497_3_fu_477_p1);

assign add_ln26_1_fu_405_p2 = (trunc_ln213_1_fu_401_p1 + 13'd511);

assign add_ln26_2_fu_934_p2 = (trunc_ln213_2_fu_930_p1 + 13'd511);

assign add_ln26_3_fu_975_p2 = (trunc_ln213_3_fu_971_p1 + 13'd511);

assign add_ln26_4_fu_1211_p2 = (trunc_ln213_4_fu_1207_p1 + 13'd511);

assign add_ln26_5_fu_1549_p2 = (trunc_ln213_5_fu_1545_p1 + 13'd511);

assign add_ln26_6_fu_446_p2 = (trunc_ln213_6_fu_442_p1 + 13'd511);

assign add_ln26_fu_581_p2 = (trunc_ln213_fu_577_p1 + 13'd511);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign b_V_fu_1579_p2 = (sub_ln213_26_fu_1575_p2 + select_ln213_12_fu_1567_p3);

assign c_V_fu_1611_p2 = (shl_ln213_6_fu_1598_p2 - select_ln213_13_fu_1603_p3);

assign grp_fu_1634_p0 = zext_ln1345_1_fu_74_p1;

assign grp_fu_1634_p1 = zext_ln1345_1_fu_74_p1;

assign grp_fu_1643_p0 = grp_fu_1643_p00;

assign grp_fu_1643_p00 = p_z_int_reg;

assign grp_fu_1643_p1 = zext_ln1345_1_fu_74_p1;

assign grp_fu_1652_p0 = zext_ln1345_fu_82_p1;

assign grp_fu_1652_p1 = zext_ln1345_fu_82_p1;

assign grp_fu_1661_p0 = zext_ln1345_2_fu_595_p1;

assign grp_fu_1661_p1 = zext_ln1345_2_fu_595_p1;

assign grp_fu_1670_p0 = zext_ln1345_3_fu_598_p1;

assign grp_fu_1670_p1 = zext_ln1345_3_fu_598_p1;

assign grp_fu_1679_p0 = zext_ln1345_4_fu_669_p1;

assign grp_fu_1679_p1 = zext_ln1345_4_fu_669_p1;

assign grp_fu_1688_p0 = grp_fu_1688_p00;

assign grp_fu_1688_p00 = y_V_37_fu_1297_p2;

assign grp_fu_1688_p1 = zext_ln1345_4_reg_1840_pp0_iter15_reg;

assign icmp_ln878_1_fu_1158_p2 = ((ret_5_fu_1150_p3 < 14'd7681) ? 1'b1 : 1'b0);

assign icmp_ln878_2_fu_611_p2 = ((ret_6_fu_604_p3 < 14'd7681) ? 1'b1 : 1'b0);

assign icmp_ln878_3_fu_646_p2 = ((ret_7_fu_640_p2 < 14'd7681) ? 1'b1 : 1'b0);

assign icmp_ln878_4_fu_1233_p2 = ((ret_9_fu_1225_p3 < 14'd7681) ? 1'b1 : 1'b0);

assign icmp_ln878_5_fu_1373_p2 = ((ret_10_fu_1366_p3 < 14'd7681) ? 1'b1 : 1'b0);

assign icmp_ln878_6_fu_1463_p2 = ((ret_11_fu_1456_p3 < 14'd7681) ? 1'b1 : 1'b0);

assign icmp_ln878_7_fu_1496_p2 = ((ret_12_fu_1488_p3 < 14'd7681) ? 1'b1 : 1'b0);

assign icmp_ln878_8_fu_1592_p2 = ((ret_15_fu_1585_p3 < 14'd7681) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_530_p2 = ((ret_3_fu_524_p2 < 14'd7681) ? 1'b1 : 1'b0);

assign icmp_ln882_10_fu_948_p2 = ((y_V_20_reg_1886 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_11_fu_965_p2 = ((y_V_22_fu_958_p3 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_12_fu_1121_p2 = ((y_V_27_fu_1115_p2 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_13_fu_1184_p2 = ((y_V_29_reg_1933 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_14_fu_1201_p2 = ((y_V_31_fu_1194_p3 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_15_fu_1436_p2 = ((y_V_38_fu_1430_p2 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_16_fu_1522_p2 = ((y_V_40_reg_1992 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_17_fu_1539_p2 = ((y_V_42_fu_1532_p3 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_18_fu_299_p2 = ((y_V_43_fu_293_p2 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_19_fu_419_p2 = ((y_V_45_reg_1760 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_1_fu_554_p2 = ((y_V_2_reg_1796 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_20_fu_436_p2 = ((y_V_47_fu_429_p3 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_2_fu_571_p2 = ((y_V_4_fu_564_p3 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_3_fu_241_p2 = ((y_V_5_fu_235_p2 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_4_fu_378_p2 = ((y_V_7_reg_1753 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_5_fu_395_p2 = ((y_V_9_fu_388_p3 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_6_fu_829_p2 = ((y_V_11_fu_823_p2 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_7_fu_907_p2 = ((y_V_13_reg_1879 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_8_fu_924_p2 = ((y_V_15_fu_917_p3 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_9_fu_887_p2 = ((y_V_18_fu_881_p2 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln882_fu_498_p2 = ((y_V_fu_492_p2 > 26'd7680) ? 1'b1 : 1'b0);

assign icmp_ln886_1_fu_1070_p2 = ((x_V_2_fu_1064_p2 > y_V_52_reg_1893) ? 1'b1 : 1'b0);

assign icmp_ln886_2_fu_1257_p2 = ((x_V_8_reg_1947 > y_V_33_fu_1251_p2) ? 1'b1 : 1'b0);

assign icmp_ln886_3_fu_1281_p2 = ((y_V_55_reg_1940_pp0_iter15_reg > y_V_56_reg_1958) ? 1'b1 : 1'b0);

assign icmp_ln886_4_fu_1563_p2 = ((x_V_12_reg_2005 > y_V_48_reg_1999) ? 1'b1 : 1'b0);

assign icmp_ln886_fu_1048_p2 = ((x_V_1_reg_1901 > y_V_51_reg_1808_pp0_iter12_reg) ? 1'b1 : 1'b0);

assign r_10_fu_1401_p3 = {{trunc_ln1497_24_reg_1981}, {13'd0}};

assign r_11_fu_1408_p3 = {{t_V_4_reg_1975}, {9'd0}};

assign r_12_fu_264_p3 = {{trunc_ln1497_25_reg_1748}, {13'd0}};

assign r_13_fu_271_p3 = {{t_V_5_reg_1742}, {9'd0}};

assign r_1_fu_470_p3 = {{t_reg_1772}, {9'd0}};

assign r_2_fu_206_p3 = {{trunc_ln1497_20_reg_1732}, {13'd0}};

assign r_3_fu_213_p3 = {{t_V_reg_1726}, {9'd0}};

assign r_4_fu_794_p3 = {{trunc_ln1497_21_reg_1858}, {13'd0}};

assign r_5_fu_801_p3 = {{t_V_1_reg_1852}, {9'd0}};

assign r_6_fu_852_p3 = {{trunc_ln1497_22_reg_1874}, {13'd0}};

assign r_7_fu_859_p3 = {{t_V_2_reg_1868}, {9'd0}};

assign r_8_fu_1086_p3 = {{trunc_ln1497_23_reg_1918}, {13'd0}};

assign r_9_fu_1093_p3 = {{t_V_3_reg_1912}, {9'd0}};

assign r_fu_463_p3 = {{trunc_ln1497_reg_1778}, {13'd0}};

assign ret_10_fu_1366_p3 = {{y_V_52_reg_1893_pp0_iter19_reg}, {1'd0}};

assign ret_11_fu_1456_p3 = {{y_V_57_reg_1986}, {1'd0}};

assign ret_12_fu_1488_p3 = {{y_V_58_fu_1482_p2}, {1'd0}};

assign ret_15_fu_1585_p3 = {{select_ln26_reg_1790_pp0_iter21_reg}, {1'd0}};

assign ret_3_fu_524_p2 = (zext_ln215_1_fu_521_p1 + zext_ln215_fu_518_p1);

assign ret_5_fu_1150_p3 = {{y_V_53_fu_1145_p2}, {1'd0}};

assign ret_6_fu_604_p3 = {{y_V_51_reg_1808}, {1'd0}};

assign ret_7_fu_640_p2 = (zext_ln1346_1_fu_636_p1 + zext_ln1346_fu_601_p1);

assign ret_9_fu_1225_p3 = {{y_V_55_fu_1178_p2}, {1'd0}};

assign select_ln213_10_fu_1474_p3 = ((icmp_ln878_6_fu_1463_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_11_fu_1508_p3 = ((icmp_ln878_7_fu_1496_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_12_fu_1567_p3 = ((icmp_ln886_4_fu_1563_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_13_fu_1603_p3 = ((icmp_ln878_8_fu_1592_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_1_fu_1052_p3 = ((icmp_ln886_fu_1048_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_2_fu_1075_p3 = ((icmp_ln886_1_fu_1070_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_3_fu_1170_p3 = ((icmp_ln878_1_fu_1158_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_4_fu_622_p3 = ((icmp_ln878_2_fu_611_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_5_fu_656_p3 = ((icmp_ln878_3_reg_1835[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_6_fu_1244_p3 = ((icmp_ln878_4_reg_1953[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_7_fu_1262_p3 = ((icmp_ln886_2_fu_1257_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_8_fu_1285_p3 = ((icmp_ln886_3_fu_1281_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_9_fu_1384_p3 = ((icmp_ln878_5_fu_1373_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln213_fu_540_p3 = ((icmp_ln878_fu_530_p2[0:0] == 1'b1) ? 13'd0 : 13'd7681);

assign select_ln26_fu_452_p3 = ((icmp_ln882_20_fu_436_p2[0:0] == 1'b1) ? add_ln26_6_fu_446_p2 : trunc_ln213_6_fu_442_p1);

assign shl_ln213_1_fu_617_p2 = y_V_51_reg_1808 << 13'd1;

assign shl_ln213_2_fu_1239_p2 = y_V_55_reg_1940 << 13'd1;

assign shl_ln213_3_fu_1379_p2 = y_V_52_reg_1893_pp0_iter19_reg << 13'd1;

assign shl_ln213_4_fu_1469_p2 = y_V_57_reg_1986 << 13'd1;

assign shl_ln213_5_fu_1502_p2 = y_V_58_fu_1482_p2 << 13'd1;

assign shl_ln213_6_fu_1598_p2 = select_ln26_reg_1790_pp0_iter21_reg << 13'd1;

assign shl_ln213_fu_1164_p2 = y_V_53_fu_1145_p2 << 13'd1;

assign sub_ln213_11_fu_1141_p2 = (x_V_2_reg_1923 - y_V_52_reg_1893_pp0_iter13_reg);

assign sub_ln213_15_fu_1104_p2 = (ret_8_reg_1907 - zext_ln21_4_fu_1083_p1);

assign sub_ln213_18_fu_1293_p2 = (y_V_55_reg_1940_pp0_iter15_reg - y_V_56_reg_1958);

assign sub_ln213_1_fu_481_p2 = (ret_reg_1767 - zext_ln21_fu_460_p1);

assign sub_ln213_22_fu_1419_p2 = (ret_13_reg_1970 - zext_ln21_5_fu_1398_p1);

assign sub_ln213_24_fu_282_p2 = (ret_14_reg_1737 - zext_ln21_6_fu_261_p1);

assign sub_ln213_26_fu_1575_p2 = (x_V_12_reg_2005 - y_V_48_reg_1999);

assign sub_ln213_3_fu_224_p2 = (ret_1_reg_1721 - zext_ln21_1_fu_203_p1);

assign sub_ln213_5_fu_1270_p2 = (x_V_8_reg_1947 - y_V_33_fu_1251_p2);

assign sub_ln213_6_fu_812_p2 = (ret_2_reg_1847 - zext_ln21_2_fu_791_p1);

assign sub_ln213_9_fu_870_p2 = (ret_4_reg_1863 - zext_ln21_3_fu_849_p1);

assign sub_ln213_fu_1060_p2 = (x_V_1_reg_1901 - y_V_51_reg_1808_pp0_iter12_reg);

assign t_V_1_fu_722_p2 = (zext_ln208_2_fu_718_p1 + zext_ln1497_8_fu_682_p1);

assign t_V_2_fu_781_p2 = (zext_ln208_3_fu_777_p1 + zext_ln1497_12_fu_741_p1);

assign t_V_3_fu_1038_p2 = (zext_ln208_4_fu_1034_p1 + zext_ln1497_16_fu_998_p1);

assign t_V_4_fu_1356_p2 = (zext_ln208_5_fu_1352_p1 + zext_ln1497_20_fu_1316_p1);

assign t_V_5_fu_193_p2 = (zext_ln208_6_fu_189_p1 + zext_ln1497_24_fu_153_p1);

assign t_V_fu_134_p2 = (zext_ln208_1_fu_130_p1 + zext_ln1497_4_fu_94_p1);

assign t_fu_368_p2 = (zext_ln208_fu_364_p1 + zext_ln1497_fu_328_p1);

assign trunc_ln1497_10_fu_758_p4 = {{grp_fu_1670_p2[25:21]}};

assign trunc_ln1497_11_fu_989_p4 = {{grp_fu_1679_p2[25:13]}};

assign trunc_ln1497_12_fu_1002_p4 = {{grp_fu_1679_p2[25:17]}};

assign trunc_ln1497_13_fu_1015_p4 = {{grp_fu_1679_p2[25:21]}};

assign trunc_ln1497_14_fu_1307_p4 = {{grp_fu_1688_p2[25:13]}};

assign trunc_ln1497_15_fu_1320_p4 = {{grp_fu_1688_p2[25:17]}};

assign trunc_ln1497_16_fu_1333_p4 = {{grp_fu_1688_p2[25:21]}};

assign trunc_ln1497_17_fu_144_p4 = {{grp_fu_1643_p2[25:13]}};

assign trunc_ln1497_18_fu_157_p4 = {{grp_fu_1643_p2[25:17]}};

assign trunc_ln1497_19_fu_170_p4 = {{grp_fu_1643_p2[25:21]}};

assign trunc_ln1497_1_fu_332_p4 = {{grp_fu_1652_p2[25:17]}};

assign trunc_ln1497_20_fu_140_p1 = t_V_fu_134_p2[12:0];

assign trunc_ln1497_21_fu_728_p1 = t_V_1_fu_722_p2[12:0];

assign trunc_ln1497_22_fu_787_p1 = t_V_2_fu_781_p2[12:0];

assign trunc_ln1497_23_fu_1044_p1 = t_V_3_fu_1038_p2[12:0];

assign trunc_ln1497_24_fu_1362_p1 = t_V_4_fu_1356_p2[12:0];

assign trunc_ln1497_25_fu_199_p1 = t_V_5_fu_193_p2[12:0];

assign trunc_ln1497_2_fu_345_p4 = {{grp_fu_1652_p2[25:21]}};

assign trunc_ln1497_3_fu_85_p4 = {{grp_fu_1634_p2[25:13]}};

assign trunc_ln1497_4_fu_98_p4 = {{grp_fu_1634_p2[25:17]}};

assign trunc_ln1497_5_fu_111_p4 = {{grp_fu_1634_p2[25:21]}};

assign trunc_ln1497_6_fu_673_p4 = {{grp_fu_1661_p2[25:13]}};

assign trunc_ln1497_7_fu_686_p4 = {{grp_fu_1661_p2[25:17]}};

assign trunc_ln1497_8_fu_699_p4 = {{grp_fu_1661_p2[25:21]}};

assign trunc_ln1497_9_fu_732_p4 = {{grp_fu_1670_p2[25:13]}};

assign trunc_ln1497_fu_374_p1 = t_fu_368_p2[12:0];

assign trunc_ln1497_s_fu_745_p4 = {{grp_fu_1670_p2[25:17]}};

assign trunc_ln213_1_fu_401_p1 = y_V_9_fu_388_p3[12:0];

assign trunc_ln213_2_fu_930_p1 = y_V_15_fu_917_p3[12:0];

assign trunc_ln213_3_fu_971_p1 = y_V_22_fu_958_p3[12:0];

assign trunc_ln213_4_fu_1207_p1 = y_V_31_fu_1194_p3[12:0];

assign trunc_ln213_5_fu_1545_p1 = y_V_42_fu_1532_p3[12:0];

assign trunc_ln213_6_fu_442_p1 = y_V_47_fu_429_p3[12:0];

assign trunc_ln213_fu_577_p1 = y_V_4_fu_564_p3[12:0];

assign trunc_ln_fu_319_p4 = {{grp_fu_1652_p2[25:13]}};

assign x_V_12_fu_1555_p3 = ((icmp_ln882_17_fu_1539_p2[0:0] == 1'b1) ? add_ln26_5_fu_1549_p2 : trunc_ln213_5_fu_1545_p1);

assign x_V_1_fu_981_p3 = ((icmp_ln882_11_fu_965_p2[0:0] == 1'b1) ? add_ln26_3_fu_975_p2 : trunc_ln213_3_fu_971_p1);

assign x_V_2_fu_1064_p2 = (select_ln213_1_fu_1052_p3 + sub_ln213_fu_1060_p2);

assign x_V_5_fu_630_p2 = (shl_ln213_1_fu_617_p2 - select_ln213_4_fu_622_p3);

assign x_V_8_fu_1217_p3 = ((icmp_ln882_14_fu_1201_p2[0:0] == 1'b1) ? add_ln26_4_fu_1211_p2 : trunc_ln213_4_fu_1207_p1);

assign y_V_11_fu_823_p2 = (add_ln213_6_fu_817_p2 - r_4_fu_794_p3);

assign y_V_12_fu_835_p2 = ($signed(y_V_11_fu_823_p2) + $signed(26'd67101183));

assign y_V_13_fu_841_p3 = ((icmp_ln882_6_fu_829_p2[0:0] == 1'b1) ? y_V_12_fu_835_p2 : y_V_11_fu_823_p2);

assign y_V_14_fu_912_p2 = ($signed(y_V_13_reg_1879) + $signed(26'd67101183));

assign y_V_15_fu_917_p3 = ((icmp_ln882_7_fu_907_p2[0:0] == 1'b1) ? y_V_14_fu_912_p2 : y_V_13_reg_1879);

assign y_V_18_fu_881_p2 = (add_ln213_10_fu_875_p2 - r_6_fu_852_p3);

assign y_V_19_fu_893_p2 = ($signed(y_V_18_fu_881_p2) + $signed(26'd67101183));

assign y_V_1_fu_504_p2 = ($signed(y_V_fu_492_p2) + $signed(26'd67101183));

assign y_V_20_fu_899_p3 = ((icmp_ln882_9_fu_887_p2[0:0] == 1'b1) ? y_V_19_fu_893_p2 : y_V_18_fu_881_p2);

assign y_V_21_fu_953_p2 = ($signed(y_V_20_reg_1886) + $signed(26'd67101183));

assign y_V_22_fu_958_p3 = ((icmp_ln882_10_fu_948_p2[0:0] == 1'b1) ? y_V_21_fu_953_p2 : y_V_20_reg_1886);

assign y_V_27_fu_1115_p2 = (add_ln213_16_fu_1109_p2 - r_8_fu_1086_p3);

assign y_V_28_fu_1127_p2 = ($signed(y_V_27_fu_1115_p2) + $signed(26'd67101183));

assign y_V_29_fu_1133_p3 = ((icmp_ln882_12_fu_1121_p2[0:0] == 1'b1) ? y_V_28_fu_1127_p2 : y_V_27_fu_1115_p2);

assign y_V_2_fu_510_p3 = ((icmp_ln882_fu_498_p2[0:0] == 1'b1) ? y_V_1_fu_504_p2 : y_V_fu_492_p2);

assign y_V_30_fu_1189_p2 = ($signed(y_V_29_reg_1933) + $signed(26'd67101183));

assign y_V_31_fu_1194_p3 = ((icmp_ln882_13_fu_1184_p2[0:0] == 1'b1) ? y_V_30_fu_1189_p2 : y_V_29_reg_1933);

assign y_V_33_fu_1251_p2 = (shl_ln213_2_fu_1239_p2 - select_ln213_6_fu_1244_p3);

assign y_V_37_fu_1297_p2 = (sub_ln213_18_fu_1293_p2 + select_ln213_8_fu_1285_p3);

assign y_V_38_fu_1430_p2 = (add_ln213_21_fu_1424_p2 - r_10_fu_1401_p3);

assign y_V_39_fu_1442_p2 = ($signed(y_V_38_fu_1430_p2) + $signed(26'd67101183));

assign y_V_3_fu_559_p2 = ($signed(y_V_2_reg_1796) + $signed(26'd67101183));

assign y_V_40_fu_1448_p3 = ((icmp_ln882_15_fu_1436_p2[0:0] == 1'b1) ? y_V_39_fu_1442_p2 : y_V_38_fu_1430_p2);

assign y_V_41_fu_1527_p2 = ($signed(y_V_40_reg_1992) + $signed(26'd67101183));

assign y_V_42_fu_1532_p3 = ((icmp_ln882_16_fu_1522_p2[0:0] == 1'b1) ? y_V_41_fu_1527_p2 : y_V_40_reg_1992);

assign y_V_43_fu_293_p2 = (add_ln213_24_fu_287_p2 - r_12_fu_264_p3);

assign y_V_44_fu_305_p2 = ($signed(y_V_43_fu_293_p2) + $signed(26'd67101183));

assign y_V_45_fu_311_p3 = ((icmp_ln882_18_fu_299_p2[0:0] == 1'b1) ? y_V_44_fu_305_p2 : y_V_43_fu_293_p2);

assign y_V_46_fu_424_p2 = ($signed(y_V_45_reg_1760) + $signed(26'd67101183));

assign y_V_47_fu_429_p3 = ((icmp_ln882_19_fu_419_p2[0:0] == 1'b1) ? y_V_46_fu_424_p2 : y_V_45_reg_1760);

assign y_V_48_fu_1516_p2 = (shl_ln213_5_fu_1502_p2 - select_ln213_11_fu_1508_p3);

assign y_V_49_fu_411_p3 = ((icmp_ln882_5_fu_395_p2[0:0] == 1'b1) ? add_ln26_1_fu_405_p2 : trunc_ln213_1_fu_401_p1);

assign y_V_4_fu_564_p3 = ((icmp_ln882_1_fu_554_p2[0:0] == 1'b1) ? y_V_3_fu_559_p2 : y_V_2_reg_1796);

assign y_V_50_fu_548_p2 = (add_ln213_9_fu_536_p2 - select_ln213_fu_540_p3);

assign y_V_51_fu_587_p3 = ((icmp_ln882_2_fu_571_p2[0:0] == 1'b1) ? add_ln26_fu_581_p2 : trunc_ln213_fu_577_p1);

assign y_V_52_fu_940_p3 = ((icmp_ln882_8_fu_924_p2[0:0] == 1'b1) ? add_ln26_2_fu_934_p2 : trunc_ln213_2_fu_930_p1);

assign y_V_53_fu_1145_p2 = (sub_ln213_11_fu_1141_p2 + select_ln213_2_reg_1928);

assign y_V_54_fu_663_p2 = (add_ln213_15_fu_652_p2 - select_ln213_5_fu_656_p3);

assign y_V_55_fu_1178_p2 = (shl_ln213_fu_1164_p2 - select_ln213_3_fu_1170_p3);

assign y_V_56_fu_1275_p2 = (select_ln213_7_fu_1262_p3 + sub_ln213_5_fu_1270_p2);

assign y_V_57_fu_1392_p2 = (shl_ln213_3_fu_1379_p2 - select_ln213_9_fu_1384_p3);

assign y_V_58_fu_1482_p2 = (shl_ln213_4_fu_1469_p2 - select_ln213_10_fu_1474_p3);

assign y_V_5_fu_235_p2 = (add_ln213_3_fu_229_p2 - r_2_fu_206_p3);

assign y_V_6_fu_247_p2 = ($signed(y_V_5_fu_235_p2) + $signed(26'd67101183));

assign y_V_7_fu_253_p3 = ((icmp_ln882_3_fu_241_p2[0:0] == 1'b1) ? y_V_6_fu_247_p2 : y_V_5_fu_235_p2);

assign y_V_8_fu_383_p2 = ($signed(y_V_7_reg_1753) + $signed(26'd67101183));

assign y_V_9_fu_388_p3 = ((icmp_ln882_4_fu_378_p2[0:0] == 1'b1) ? y_V_8_fu_383_p2 : y_V_7_reg_1753);

assign y_V_fu_492_p2 = (add_ln213_fu_486_p2 - r_fu_463_p3);

assign zext_ln1345_1_fu_74_p1 = p_y_int_reg;

assign zext_ln1345_2_fu_595_p1 = y_V_49_reg_1783_pp0_iter6_reg;

assign zext_ln1345_3_fu_598_p1 = y_V_50_reg_1803;

assign zext_ln1345_4_fu_669_p1 = y_V_54_fu_663_p2;

assign zext_ln1345_fu_82_p1 = p_x_read_reg_1696_pp0_iter1_reg;

assign zext_ln1346_1_fu_636_p1 = x_V_5_fu_630_p2;

assign zext_ln1346_fu_601_p1 = y_V_51_reg_1808;

assign zext_ln1497_10_fu_708_p1 = trunc_ln1497_8_fu_699_p4;

assign zext_ln1497_11_fu_808_p1 = r_5_fu_801_p3;

assign zext_ln1497_12_fu_741_p1 = trunc_ln1497_9_fu_732_p4;

assign zext_ln1497_13_fu_754_p1 = trunc_ln1497_s_fu_745_p4;

assign zext_ln1497_14_fu_767_p1 = trunc_ln1497_10_fu_758_p4;

assign zext_ln1497_15_fu_866_p1 = r_7_fu_859_p3;

assign zext_ln1497_16_fu_998_p1 = trunc_ln1497_11_fu_989_p4;

assign zext_ln1497_17_fu_1011_p1 = trunc_ln1497_12_fu_1002_p4;

assign zext_ln1497_18_fu_1024_p1 = trunc_ln1497_13_fu_1015_p4;

assign zext_ln1497_19_fu_1100_p1 = r_9_fu_1093_p3;

assign zext_ln1497_1_fu_341_p1 = trunc_ln1497_1_fu_332_p4;

assign zext_ln1497_20_fu_1316_p1 = trunc_ln1497_14_fu_1307_p4;

assign zext_ln1497_21_fu_1329_p1 = trunc_ln1497_15_fu_1320_p4;

assign zext_ln1497_22_fu_1342_p1 = trunc_ln1497_16_fu_1333_p4;

assign zext_ln1497_23_fu_1415_p1 = r_11_fu_1408_p3;

assign zext_ln1497_24_fu_153_p1 = trunc_ln1497_17_fu_144_p4;

assign zext_ln1497_25_fu_166_p1 = trunc_ln1497_18_fu_157_p4;

assign zext_ln1497_26_fu_179_p1 = trunc_ln1497_19_fu_170_p4;

assign zext_ln1497_27_fu_278_p1 = r_13_fu_271_p3;

assign zext_ln1497_2_fu_354_p1 = trunc_ln1497_2_fu_345_p4;

assign zext_ln1497_3_fu_477_p1 = r_1_fu_470_p3;

assign zext_ln1497_4_fu_94_p1 = trunc_ln1497_3_fu_85_p4;

assign zext_ln1497_5_fu_107_p1 = trunc_ln1497_4_fu_98_p4;

assign zext_ln1497_6_fu_120_p1 = trunc_ln1497_5_fu_111_p4;

assign zext_ln1497_7_fu_220_p1 = r_3_fu_213_p3;

assign zext_ln1497_8_fu_682_p1 = trunc_ln1497_6_fu_673_p4;

assign zext_ln1497_9_fu_695_p1 = trunc_ln1497_7_fu_686_p4;

assign zext_ln1497_fu_328_p1 = trunc_ln_fu_319_p4;

assign zext_ln208_1_fu_130_p1 = add_ln208_2_fu_124_p2;

assign zext_ln208_2_fu_718_p1 = add_ln208_4_fu_712_p2;

assign zext_ln208_3_fu_777_p1 = add_ln208_6_fu_771_p2;

assign zext_ln208_4_fu_1034_p1 = add_ln208_8_fu_1028_p2;

assign zext_ln208_5_fu_1352_p1 = add_ln208_10_fu_1346_p2;

assign zext_ln208_6_fu_189_p1 = add_ln208_12_fu_183_p2;

assign zext_ln208_fu_364_p1 = add_ln208_fu_358_p2;

assign zext_ln215_1_fu_521_p1 = y_V_49_reg_1783;

assign zext_ln215_fu_518_p1 = p_x_read_reg_1696_pp0_iter5_reg;

assign zext_ln21_1_fu_203_p1 = t_V_reg_1726;

assign zext_ln21_2_fu_791_p1 = t_V_1_reg_1852;

assign zext_ln21_3_fu_849_p1 = t_V_2_reg_1868;

assign zext_ln21_4_fu_1083_p1 = t_V_3_reg_1912;

assign zext_ln21_5_fu_1398_p1 = t_V_4_reg_1975;

assign zext_ln21_6_fu_261_p1 = t_V_5_reg_1742;

assign zext_ln21_fu_460_p1 = t_reg_1772;

always @ (posedge ap_clk) begin
    zext_ln1345_4_reg_1840[25:13] <= 13'b0000000000000;
    zext_ln1345_4_reg_1840_pp0_iter10_reg[25:13] <= 13'b0000000000000;
    zext_ln1345_4_reg_1840_pp0_iter11_reg[25:13] <= 13'b0000000000000;
    zext_ln1345_4_reg_1840_pp0_iter12_reg[25:13] <= 13'b0000000000000;
    zext_ln1345_4_reg_1840_pp0_iter13_reg[25:13] <= 13'b0000000000000;
    zext_ln1345_4_reg_1840_pp0_iter14_reg[25:13] <= 13'b0000000000000;
    zext_ln1345_4_reg_1840_pp0_iter15_reg[25:13] <= 13'b0000000000000;
    select_ln213_2_reg_1928[8:1] <= 8'b00000000;
end

endmodule //msm_arr_pdouble
