// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module msm_arr_bucket_unit_sr_Block_split153_proc7 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        num_padd_ops,
        B_i_address0,
        B_i_ce0,
        B_i_we0,
        B_i_d0,
        B_i_address1,
        B_i_ce1,
        B_i_we1,
        B_i_d1,
        BFIFO_1176_dout,
        BFIFO_1176_empty_n,
        BFIFO_1176_read,
        count_B_address0,
        count_B_ce0,
        count_B_q0,
        BFIFO_2_dout,
        BFIFO_2_empty_n,
        BFIFO_2_read,
        CFIFO_din,
        CFIFO_full_n,
        CFIFO_write,
        num_padd_ops_out_din,
        num_padd_ops_out_full_n,
        num_padd_ops_out_write
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_pp2_stage0 = 21'd4096;
parameter    ap_ST_fsm_pp2_stage1 = 21'd8192;
parameter    ap_ST_fsm_state16 = 21'd16384;
parameter    ap_ST_fsm_pp3_stage0 = 21'd32768;
parameter    ap_ST_fsm_state19 = 21'd65536;
parameter    ap_ST_fsm_state20 = 21'd131072;
parameter    ap_ST_fsm_state21 = 21'd262144;
parameter    ap_ST_fsm_state22 = 21'd524288;
parameter    ap_ST_fsm_state23 = 21'd1048576;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [12:0] num_padd_ops;
output  [4:0] B_i_address0;
output   B_i_ce0;
output   B_i_we0;
output  [31:0] B_i_d0;
output  [4:0] B_i_address1;
output   B_i_ce1;
output   B_i_we1;
output  [31:0] B_i_d1;
input  [42:0] BFIFO_1176_dout;
input   BFIFO_1176_empty_n;
output   BFIFO_1176_read;
output  [3:0] count_B_address0;
output   count_B_ce0;
input  [12:0] count_B_q0;
input  [42:0] BFIFO_2_dout;
input   BFIFO_2_empty_n;
output   BFIFO_2_read;
output  [81:0] CFIFO_din;
input   CFIFO_full_n;
output   CFIFO_write;
output  [12:0] num_padd_ops_out_din;
input   num_padd_ops_out_full_n;
output   num_padd_ops_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg[4:0] B_i_address0;
reg B_i_ce0;
reg B_i_we0;
reg[31:0] B_i_d0;
reg[4:0] B_i_address1;
reg B_i_ce1;
reg B_i_we1;
reg[31:0] B_i_d1;
reg BFIFO_1176_read;
reg[3:0] count_B_address0;
reg count_B_ce0;
reg BFIFO_2_read;
reg CFIFO_write;
reg num_padd_ops_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    BFIFO_1176_blk_n;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_pp2_stage0;
wire   [0:0] or_ln260_fu_632_p2;
wire   [0:0] icmp_ln878_fu_621_p2;
wire   [0:0] tmp_i_nbreadreq_fu_194_p3;
reg    BFIFO_2_blk_n;
wire   [0:0] icmp_ln878_14_fu_627_p2;
wire   [0:0] tmp_8_i_nbreadreq_fu_202_p3;
reg    CFIFO_blk_n;
wire    ap_CS_fsm_state22;
reg   [0:0] icmp_ln878_15_reg_1183;
reg   [0:0] or_ln315_reg_1179;
reg    num_padd_ops_out_blk_n;
reg   [4:0] i_reg_530;
reg   [3:0] nibble_K_V_reg_541;
wire   [4:0] empty_29_fu_561_p2;
wire    ap_CS_fsm_state9;
wire   [4:0] empty_32_fu_578_p2;
wire    ap_CS_fsm_state11;
reg   [12:0] count_BF2_V_2_reg_1039;
reg    ap_predicate_op113_read_state13;
reg    ap_predicate_op120_read_state13;
reg    ap_block_state13_pp2_stage0_iter0;
wire    ap_block_state15_pp2_stage0_iter1;
reg    ap_block_pp2_stage0_11001;
reg   [12:0] count_BF1_V_2_reg_1044;
reg   [0:0] icmp_ln878_reg_1049;
reg   [0:0] icmp_ln878_14_reg_1053;
reg   [0:0] or_ln260_reg_1057;
reg   [0:0] tmp_i_reg_1061;
reg   [0:0] tmp_8_i_reg_1065;
reg   [42:0] p_Val2_2_reg_1069;
wire   [3:0] lhs_V_7_fu_638_p4;
reg   [3:0] lhs_V_7_reg_1077;
reg   [3:0] padd_count_V_addr_16_reg_1082;
reg   [42:0] p_Val2_1_reg_1093;
wire   [3:0] lhs_V_fu_654_p4;
reg   [3:0] lhs_V_reg_1101;
wire   [0:0] icmp_ln870_3_fu_696_p2;
reg   [0:0] icmp_ln870_3_reg_1111;
wire    ap_CS_fsm_pp2_stage1;
wire    ap_block_state14_pp2_stage1_iter0;
wire    ap_block_pp2_stage1_11001;
wire   [0:0] icmp_ln870_fu_763_p2;
reg   [0:0] icmp_ln870_reg_1115;
wire   [0:0] icmp_ln874_fu_779_p2;
reg   [0:0] icmp_ln874_reg_1119;
reg   [3:0] bcount_addr_3_reg_1123;
reg   [3:0] fill_count_addr_2_reg_1128;
wire   [0:0] icmp_ln307_fu_865_p2;
reg   [0:0] icmp_ln307_reg_1133;
wire    ap_CS_fsm_pp3_stage0;
wire    ap_block_state17_pp3_stage0_iter0;
wire    ap_block_state18_pp3_stage0_iter1;
wire    ap_block_pp3_stage0_11001;
wire   [4:0] add_ln307_fu_871_p2;
reg    ap_enable_reg_pp3_iter0;
wire   [3:0] trunc_ln301_fu_882_p1;
reg   [3:0] trunc_ln301_reg_1147;
wire   [3:0] nibble_K_V_1_fu_902_p3;
reg    ap_enable_reg_pp3_iter1;
wire    ap_CS_fsm_state19;
reg   [3:0] bcount_addr_1_reg_1169;
wire   [31:0] num_padd_ops_cast_fu_926_p1;
reg   [31:0] num_padd_ops_cast_reg_1174;
wire    ap_CS_fsm_state20;
wire   [0:0] or_ln315_fu_945_p2;
wire   [0:0] icmp_ln878_15_fu_954_p2;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state12;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state13;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage1_subdone;
wire    ap_CS_fsm_state16;
wire    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state17;
reg   [3:0] padd_count_V_address0;
reg    padd_count_V_ce0;
reg    padd_count_V_we0;
wire   [12:0] padd_count_V_q0;
reg   [3:0] padd_count_V_address1;
reg    padd_count_V_ce1;
reg    padd_count_V_we1;
reg   [12:0] padd_count_V_d1;
reg   [3:0] bcount_address0;
reg    bcount_ce0;
reg    bcount_we0;
reg   [31:0] bcount_d0;
wire   [31:0] bcount_q0;
reg   [3:0] fill_count_address0;
reg    fill_count_ce0;
reg    fill_count_we0;
reg   [31:0] fill_count_d0;
wire   [31:0] fill_count_q0;
reg   [4:0] empty_reg_499;
wire    ap_CS_fsm_state8;
wire   [0:0] exitcond5136_i_fu_567_p2;
reg   [4:0] empty_31_reg_510;
wire   [0:0] exitcond5035_i_fu_584_p2;
wire    ap_CS_fsm_state10;
reg   [42:0] ap_phi_mux_data_V_phi_fu_524_p4;
wire   [42:0] ap_phi_reg_pp2_iter0_data_V_reg_521;
wire    ap_block_pp3_stage0;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [63:0] p_cast_i_fu_573_p1;
wire   [63:0] p_cast15_i_fu_590_p1;
wire   [63:0] zext_ln708_1_fu_648_p1;
wire   [63:0] zext_ln708_fu_664_p1;
wire   [63:0] zext_ln281_fu_729_p1;
wire    ap_block_pp2_stage1;
wire   [63:0] zext_ln282_fu_748_p1;
wire   [63:0] conv_i173_i_fu_790_p1;
wire   [63:0] zext_ln268_fu_823_p1;
wire   [63:0] zext_ln269_fu_842_p1;
wire   [63:0] i_cast_i_fu_877_p1;
wire   [63:0] conv_i135_i_fu_909_p1;
reg   [12:0] count_BF2_V_fu_164;
wire   [12:0] count_BF2_V_3_fu_669_p2;
reg   [12:0] count_BF1_V_fu_168;
wire   [12:0] count_BF1_V_3_fu_757_p2;
reg   [42:0] p_Val2_s_fu_172;
reg   [31:0] i_4_fu_176;
wire   [31:0] i_7_fu_959_p2;
reg    ap_block_state1;
reg    ap_predicate_op239_write_state22;
reg    ap_block_state22;
wire   [12:0] add_ln691_fu_675_p2;
wire   [31:0] add_ln294_fu_851_p2;
wire   [31:0] add_ln319_fu_973_p2;
wire   [31:0] add_ln295_fu_858_p2;
wire   [31:0] zext_ln358_2_fu_711_p1;
wire   [31:0] zext_ln358_3_fu_737_p1;
wire   [31:0] zext_ln358_fu_805_p1;
wire   [31:0] zext_ln358_1_fu_831_p1;
wire   [5:0] tmp_fu_611_p4;
wire   [13:0] zext_ln1347_fu_686_p1;
wire   [13:0] zext_ln870_fu_682_p1;
wire   [13:0] ret_V_21_fu_690_p2;
wire   [25:0] p_Result_4_i_fu_702_p4;
wire   [3:0] ret_V_22_fu_716_p2;
wire   [4:0] shl_ln1_fu_721_p3;
wire   [12:0] trunc_ln674_1_fu_734_p1;
wire   [4:0] or_ln282_fu_742_p2;
wire   [3:0] nibble_K_V_2_fu_769_p4;
wire   [25:0] p_Result_1_i_fu_796_p4;
wire   [3:0] ret_V_fu_810_p2;
wire   [4:0] shl_ln_fu_815_p3;
wire   [12:0] trunc_ln674_fu_828_p1;
wire   [4:0] or_ln269_fu_836_p2;
wire   [30:0] tmp_4_fu_886_p4;
wire   [0:0] icmp_ln308_fu_896_p2;
wire   [28:0] tmp_3_fu_929_p4;
wire   [0:0] lnot_i_i_i_fu_920_p2;
wire   [0:0] icmp_ln315_fu_939_p2;
wire   [38:0] trunc_ln674_2_fu_980_p1;
wire    ap_CS_fsm_state23;
reg   [20:0] ap_NS_fsm;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_condition_512;
reg    ap_condition_521;
reg    ap_condition_508;
reg    ap_condition_129;
reg    ap_condition_113;
reg    ap_condition_104;
reg    ap_condition_256;
reg    ap_condition_422;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 21'd1;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
end

msm_arr_bucket_unit_sr_Block_split153_proc7_padd_count_V #(
    .DataWidth( 13 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
padd_count_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(padd_count_V_address0),
    .ce0(padd_count_V_ce0),
    .we0(padd_count_V_we0),
    .d0(13'd0),
    .q0(padd_count_V_q0),
    .address1(padd_count_V_address1),
    .ce1(padd_count_V_ce1),
    .we1(padd_count_V_we1),
    .d1(padd_count_V_d1)
);

msm_arr_bucket_unit_sr_Block_split153_proc7_bcount #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
bcount_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bcount_address0),
    .ce0(bcount_ce0),
    .we0(bcount_we0),
    .d0(bcount_d0),
    .q0(bcount_q0)
);

msm_arr_bucket_unit_sr_Block_split153_proc7_bcount #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
fill_count_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fill_count_address0),
    .ce0(fill_count_ce0),
    .we0(fill_count_we0),
    .d0(fill_count_d0),
    .q0(fill_count_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_condition_pp2_exit_iter0_state13) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp2_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_subdone)) | ((1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_subdone)))) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp3_exit_iter0_state17) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp3_exit_iter0_state17) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
            ap_enable_reg_pp3_iter1 <= (1'b1 ^ ap_condition_pp3_exit_iter0_state17);
        end else if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_enable_reg_pp3_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        count_BF1_V_fu_168 <= 13'd0;
    end else if ((((ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln870_fu_763_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln870_fu_763_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage1) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1) & (1'b0 == ap_block_pp2_stage1_11001)))) begin
        count_BF1_V_fu_168 <= count_BF1_V_3_fu_757_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        count_BF2_V_fu_164 <= 13'd0;
    end else if ((((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & (((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & (((icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))))) begin
        count_BF2_V_fu_164 <= count_BF2_V_3_fu_669_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        empty_31_reg_510 <= 5'd0;
    end else if (((exitcond5035_i_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        empty_31_reg_510 <= empty_32_fu_578_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond5136_i_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        empty_reg_499 <= empty_29_fu_561_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        empty_reg_499 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        i_4_fu_176 <= 32'd0;
    end else if (((icmp_ln878_15_fu_954_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21) & (or_ln315_reg_1179 == 1'd0))) begin
        i_4_fu_176 <= i_7_fu_959_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        i_reg_530 <= 5'd1;
    end else if (((ap_enable_reg_pp3_iter0 == 1'b1) & (icmp_ln307_fu_865_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        i_reg_530 <= add_ln307_fu_871_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        nibble_K_V_reg_541 <= 4'd0;
    end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln307_reg_1133 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        nibble_K_V_reg_541 <= nibble_K_V_1_fu_902_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((1'b1 == ap_condition_521)) begin
            p_Val2_s_fu_172 <= p_Val2_1_reg_1093;
        end else if ((1'b1 == ap_condition_256)) begin
            p_Val2_s_fu_172 <= ap_phi_mux_data_V_phi_fu_524_p4;
        end else if ((1'b1 == ap_condition_512)) begin
            p_Val2_s_fu_172 <= p_Val2_2_reg_1069;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        bcount_addr_1_reg_1169 <= conv_i135_i_fu_909_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & ((((icmp_ln874_fu_779_p2 == 1'd0) & (icmp_ln870_fu_763_p2 == 1'd0) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1)) | ((icmp_ln874_fu_779_p2 == 1'd0) & (icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1))) | ((icmp_ln874_fu_779_p2 == 1'd0) & (icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0))))) begin
        bcount_addr_3_reg_1123 <= conv_i173_i_fu_790_p1;
        fill_count_addr_2_reg_1128 <= conv_i173_i_fu_790_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        count_BF1_V_2_reg_1044 <= count_BF1_V_fu_168;
        count_BF2_V_2_reg_1039 <= count_BF2_V_fu_164;
        icmp_ln878_14_reg_1053 <= icmp_ln878_14_fu_627_p2;
        icmp_ln878_reg_1049 <= icmp_ln878_fu_621_p2;
        or_ln260_reg_1057 <= or_ln260_fu_632_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        icmp_ln307_reg_1133 <= icmp_ln307_fu_865_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & (((tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0))))) begin
        icmp_ln870_3_reg_1111 <= icmp_ln870_3_fu_696_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage1) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1) & (1'b0 == ap_block_pp2_stage1_11001))) begin
        icmp_ln870_reg_1115 <= icmp_ln870_fu_763_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & ((((icmp_ln870_fu_763_p2 == 1'd0) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1))) | ((icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0))))) begin
        icmp_ln874_reg_1119 <= icmp_ln874_fu_779_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        icmp_ln878_15_reg_1183 <= icmp_ln878_15_fu_954_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1)) | ((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (tmp_i_nbreadreq_fu_194_p3 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1))))) begin
        lhs_V_7_reg_1077 <= {{BFIFO_2_dout[42:39]}};
        padd_count_V_addr_16_reg_1082 <= zext_ln708_1_fu_648_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (tmp_i_nbreadreq_fu_194_p3 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd1) & (or_ln260_fu_632_p2 == 1'd1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        lhs_V_reg_1101 <= {{BFIFO_1176_dout[42:39]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        num_padd_ops_cast_reg_1174[12 : 0] <= num_padd_ops_cast_fu_926_p1[12 : 0];
        or_ln315_reg_1179 <= or_ln315_fu_945_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_predicate_op120_read_state13 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        p_Val2_1_reg_1093 <= BFIFO_1176_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_predicate_op113_read_state13 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        p_Val2_2_reg_1069 <= BFIFO_2_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (((icmp_ln878_14_fu_627_p2 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1)) | ((icmp_ln878_14_fu_627_p2 == 1'd1) & (tmp_i_nbreadreq_fu_194_p3 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1))))) begin
        tmp_8_i_reg_1065 <= tmp_8_i_nbreadreq_fu_202_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln878_fu_621_p2 == 1'd1) & (or_ln260_fu_632_p2 == 1'd1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_i_reg_1061 <= tmp_i_nbreadreq_fu_194_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln307_fu_865_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        trunc_ln301_reg_1147 <= trunc_ln301_fu_882_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (tmp_i_nbreadreq_fu_194_p3 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd1) & (or_ln260_fu_632_p2 == 1'd1) & (1'b0 == ap_block_pp2_stage0))) begin
        BFIFO_1176_blk_n = BFIFO_1176_empty_n;
    end else begin
        BFIFO_1176_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_predicate_op120_read_state13 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        BFIFO_1176_read = 1'b1;
    end else begin
        BFIFO_1176_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0) & (((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1)) | ((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (tmp_i_nbreadreq_fu_194_p3 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1))))) begin
        BFIFO_2_blk_n = BFIFO_2_empty_n;
    end else begin
        BFIFO_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_predicate_op113_read_state13 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        BFIFO_2_read = 1'b1;
    end else begin
        BFIFO_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_508)) begin
        if ((1'b1 == ap_condition_521)) begin
            B_i_address0 = zext_ln269_fu_842_p1;
        end else if ((1'b1 == ap_condition_512)) begin
            B_i_address0 = zext_ln282_fu_748_p1;
        end else begin
            B_i_address0 = 'bx;
        end
    end else begin
        B_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_508)) begin
        if ((1'b1 == ap_condition_521)) begin
            B_i_address1 = zext_ln268_fu_823_p1;
        end else if ((1'b1 == ap_condition_512)) begin
            B_i_address1 = zext_ln281_fu_729_p1;
        end else begin
            B_i_address1 = 'bx;
        end
    end else begin
        B_i_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln870_fu_763_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & (((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))))) begin
        B_i_ce0 = 1'b1;
    end else begin
        B_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln870_fu_763_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & (((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))))) begin
        B_i_ce1 = 1'b1;
    end else begin
        B_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_508)) begin
        if ((1'b1 == ap_condition_521)) begin
            B_i_d0 = zext_ln358_1_fu_831_p1;
        end else if ((1'b1 == ap_condition_512)) begin
            B_i_d0 = zext_ln358_3_fu_737_p1;
        end else begin
            B_i_d0 = 'bx;
        end
    end else begin
        B_i_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_508)) begin
        if ((1'b1 == ap_condition_521)) begin
            B_i_d1 = zext_ln358_fu_805_p1;
        end else if ((1'b1 == ap_condition_512)) begin
            B_i_d1 = zext_ln358_2_fu_711_p1;
        end else begin
            B_i_d1 = 'bx;
        end
    end else begin
        B_i_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln870_fu_763_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & (((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))))) begin
        B_i_we0 = 1'b1;
    end else begin
        B_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln870_fu_763_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & (((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))))) begin
        B_i_we1 = 1'b1;
    end else begin
        B_i_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) & (or_ln315_reg_1179 == 1'd0) & (icmp_ln878_15_reg_1183 == 1'd1))) begin
        CFIFO_blk_n = CFIFO_full_n;
    end else begin
        CFIFO_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op239_write_state22 == 1'b1) & (1'b0 == CFIFO_full_n)) & (ap_predicate_op239_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        CFIFO_write = 1'b1;
    end else begin
        CFIFO_write = 1'b0;
    end
end

always @ (*) begin
    if ((or_ln260_fu_632_p2 == 1'd0)) begin
        ap_condition_pp2_exit_iter0_state13 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state13 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln307_fu_865_p2 == 1'd1)) begin
        ap_condition_pp3_exit_iter0_state17 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state17 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))) begin
        ap_phi_mux_data_V_phi_fu_524_p4 = p_Val2_2_reg_1069;
    end else if (((icmp_ln870_fu_763_p2 == 1'd0) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1))) begin
        ap_phi_mux_data_V_phi_fu_524_p4 = p_Val2_1_reg_1093;
    end else begin
        ap_phi_mux_data_V_phi_fu_524_p4 = ap_phi_reg_pp2_iter0_data_V_reg_521;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        bcount_address0 = bcount_addr_1_reg_1169;
    end else if (((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        bcount_address0 = i_cast_i_fu_877_p1;
    end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        bcount_address0 = bcount_addr_3_reg_1123;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1))) begin
        bcount_address0 = conv_i173_i_fu_790_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        bcount_address0 = p_cast_i_fu_573_p1;
    end else begin
        bcount_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state9) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | (~((ap_predicate_op239_write_state22 == 1'b1) & (1'b0 == CFIFO_full_n)) & (1'b1 == ap_CS_fsm_state22)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        bcount_ce0 = 1'b1;
    end else begin
        bcount_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bcount_d0 = add_ln319_fu_973_p2;
    end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        bcount_d0 = add_ln294_fu_851_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        bcount_d0 = 32'd0;
    end else begin
        bcount_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & ((((icmp_ln874_reg_1119 == 1'd0) & (icmp_ln870_reg_1115 == 1'd0) & (tmp_i_reg_1061 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1)) | ((icmp_ln874_reg_1119 == 1'd0) & (icmp_ln870_3_reg_1111 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (icmp_ln878_14_reg_1053 == 1'd1))) | ((icmp_ln874_reg_1119 == 1'd0) & (icmp_ln870_3_reg_1111 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))) | (~((ap_predicate_op239_write_state22 == 1'b1) & (1'b0 == CFIFO_full_n)) & (1'b1 == ap_CS_fsm_state22) & (or_ln315_reg_1179 == 1'd0) & (icmp_ln878_15_reg_1183 == 1'd1)) | ((exitcond5136_i_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9)))) begin
        bcount_we0 = 1'b1;
    end else begin
        bcount_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_104)) begin
        if ((1'b1 == ap_condition_113)) begin
            count_B_address0 = zext_ln708_fu_664_p1;
        end else if ((1'b1 == ap_condition_129)) begin
            count_B_address0 = zext_ln708_1_fu_648_p1;
        end else begin
            count_B_address0 = 'bx;
        end
    end else begin
        count_B_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1)) | ((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (tmp_i_nbreadreq_fu_194_p3 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1)))) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (tmp_i_nbreadreq_fu_194_p3 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd1) & (or_ln260_fu_632_p2 == 1'd1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        count_B_ce0 = 1'b1;
    end else begin
        count_B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        fill_count_address0 = conv_i135_i_fu_909_p1;
    end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        fill_count_address0 = fill_count_addr_2_reg_1128;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1))) begin
        fill_count_address0 = conv_i173_i_fu_790_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        fill_count_address0 = p_cast15_i_fu_590_p1;
    end else begin
        fill_count_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state11) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        fill_count_ce0 = 1'b1;
    end else begin
        fill_count_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        fill_count_d0 = add_ln295_fu_858_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        fill_count_d0 = 32'd0;
    end else begin
        fill_count_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & ((((icmp_ln874_reg_1119 == 1'd0) & (icmp_ln870_reg_1115 == 1'd0) & (tmp_i_reg_1061 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1)) | ((icmp_ln874_reg_1119 == 1'd0) & (icmp_ln870_3_reg_1111 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (icmp_ln878_14_reg_1053 == 1'd1))) | ((icmp_ln874_reg_1119 == 1'd0) & (icmp_ln870_3_reg_1111 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))) | ((exitcond5035_i_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        fill_count_we0 = 1'b1;
    end else begin
        fill_count_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_padd_ops_out_blk_n = num_padd_ops_out_full_n;
    end else begin
        num_padd_ops_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((num_padd_ops_out_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_padd_ops_out_write = 1'b1;
    end else begin
        num_padd_ops_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        padd_count_V_address0 = zext_ln708_1_fu_648_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        padd_count_V_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        padd_count_V_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        padd_count_V_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        padd_count_V_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        padd_count_V_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        padd_count_V_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        padd_count_V_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        padd_count_V_address0 = 64'd1;
    end else begin
        padd_count_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1))) begin
        padd_count_V_address1 = padd_count_V_addr_16_reg_1082;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        padd_count_V_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        padd_count_V_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        padd_count_V_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        padd_count_V_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        padd_count_V_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        padd_count_V_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        padd_count_V_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        padd_count_V_address1 = 64'd0;
    end else begin
        padd_count_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | (~((num_padd_ops_out_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        padd_count_V_ce0 = 1'b1;
    end else begin
        padd_count_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001)) | (~((num_padd_ops_out_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        padd_count_V_ce1 = 1'b1;
    end else begin
        padd_count_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1))) begin
        padd_count_V_d1 = add_ln691_fu_675_p2;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8))) begin
        padd_count_V_d1 = 13'd0;
    end else begin
        padd_count_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (~((num_padd_ops_out_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        padd_count_V_we0 = 1'b1;
    end else begin
        padd_count_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001) & (((tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)))) | (~((num_padd_ops_out_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        padd_count_V_we1 = 1'b1;
    end else begin
        padd_count_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((num_padd_ops_out_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((exitcond5136_i_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((exitcond5035_i_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((ap_enable_reg_pp2_iter0 == 1'b1) & (or_ln260_fu_632_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_subdone)) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (or_ln260_fu_632_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_pp2_stage1 : begin
            if ((1'b0 == ap_block_pp2_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_pp3_stage0;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if (~((ap_enable_reg_pp3_iter0 == 1'b1) & (icmp_ln307_fu_865_p2 == 1'd1) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((ap_enable_reg_pp3_iter0 == 1'b1) & (icmp_ln307_fu_865_p2 == 1'd1) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((icmp_ln878_15_fu_954_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state22 : begin
            if ((~((ap_predicate_op239_write_state22 == 1'b1) & (1'b0 == CFIFO_full_n)) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CFIFO_din = {{{nibble_K_V_reg_541}, {39'd0}}, {trunc_ln674_2_fu_980_p1}};

assign add_ln294_fu_851_p2 = (bcount_q0 + 32'd1);

assign add_ln295_fu_858_p2 = (fill_count_q0 + 32'd1);

assign add_ln307_fu_871_p2 = (i_reg_530 + 5'd1);

assign add_ln319_fu_973_p2 = ($signed(bcount_q0) + $signed(32'd4294967294));

assign add_ln691_fu_675_p2 = (padd_count_V_q0 + 13'd1);

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp2_stage1 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((ap_enable_reg_pp2_iter0 == 1'b1) & (((1'b0 == BFIFO_1176_empty_n) & (ap_predicate_op120_read_state13 == 1'b1)) | ((1'b0 == BFIFO_2_empty_n) & (ap_predicate_op113_read_state13 == 1'b1))));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((ap_enable_reg_pp2_iter0 == 1'b1) & (((1'b0 == BFIFO_1176_empty_n) & (ap_predicate_op120_read_state13 == 1'b1)) | ((1'b0 == BFIFO_2_empty_n) & (ap_predicate_op113_read_state13 == 1'b1))));
end

assign ap_block_pp2_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((num_padd_ops_out_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state13_pp2_stage0_iter0 = (((1'b0 == BFIFO_1176_empty_n) & (ap_predicate_op120_read_state13 == 1'b1)) | ((1'b0 == BFIFO_2_empty_n) & (ap_predicate_op113_read_state13 == 1'b1)));
end

assign ap_block_state14_pp2_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state22 = ((ap_predicate_op239_write_state22 == 1'b1) & (1'b0 == CFIFO_full_n));
end

always @ (*) begin
    ap_condition_104 = ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0));
end

always @ (*) begin
    ap_condition_113 = ((tmp_i_nbreadreq_fu_194_p3 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd1) & (or_ln260_fu_632_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_129 = (((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1)) | ((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (tmp_i_nbreadreq_fu_194_p3 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_256 = ((((icmp_ln870_fu_763_p2 == 1'd0) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1))) | ((icmp_ln870_3_fu_696_p2 == 1'd0) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)));
end

always @ (*) begin
    ap_condition_422 = ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001));
end

always @ (*) begin
    ap_condition_508 = ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1));
end

always @ (*) begin
    ap_condition_512 = (((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (tmp_i_reg_1061 == 1'd0) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1)) | ((icmp_ln870_3_fu_696_p2 == 1'd1) & (tmp_8_i_reg_1065 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_14_reg_1053 == 1'd1) & (icmp_ln878_reg_1049 == 1'd0)));
end

always @ (*) begin
    ap_condition_521 = ((icmp_ln870_fu_763_p2 == 1'd1) & (tmp_i_reg_1061 == 1'd1) & (or_ln260_reg_1057 == 1'd1) & (icmp_ln878_reg_1049 == 1'd1));
end

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_phi_reg_pp2_iter0_data_V_reg_521 = 'bx;

always @ (*) begin
    ap_predicate_op113_read_state13 = (((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1)) | ((tmp_8_i_nbreadreq_fu_202_p3 == 1'd1) & (icmp_ln878_14_fu_627_p2 == 1'd1) & (tmp_i_nbreadreq_fu_194_p3 == 1'd0) & (or_ln260_fu_632_p2 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op120_read_state13 = ((tmp_i_nbreadreq_fu_194_p3 == 1'd1) & (icmp_ln878_fu_621_p2 == 1'd1) & (or_ln260_fu_632_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op239_write_state22 = ((or_ln315_reg_1179 == 1'd0) & (icmp_ln878_15_reg_1183 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign conv_i135_i_fu_909_p1 = nibble_K_V_reg_541;

assign conv_i173_i_fu_790_p1 = nibble_K_V_2_fu_769_p4;

assign count_BF1_V_3_fu_757_p2 = (count_BF1_V_2_reg_1044 + 13'd1);

assign count_BF2_V_3_fu_669_p2 = (count_BF2_V_2_reg_1039 + 13'd1);

assign empty_29_fu_561_p2 = (empty_reg_499 + 5'd1);

assign empty_32_fu_578_p2 = (empty_31_reg_510 + 5'd1);

assign exitcond5035_i_fu_584_p2 = ((empty_31_reg_510 == 5'd16) ? 1'b1 : 1'b0);

assign exitcond5136_i_fu_567_p2 = ((empty_reg_499 == 5'd16) ? 1'b1 : 1'b0);

assign i_7_fu_959_p2 = (i_4_fu_176 + 32'd1);

assign i_cast_i_fu_877_p1 = i_reg_530;

assign icmp_ln307_fu_865_p2 = ((i_reg_530 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln308_fu_896_p2 = (($signed(tmp_4_fu_886_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln315_fu_939_p2 = (($signed(tmp_3_fu_929_p4) < $signed(29'd1)) ? 1'b1 : 1'b0);

assign icmp_ln870_3_fu_696_p2 = ((zext_ln870_fu_682_p1 == ret_V_21_fu_690_p2) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_763_p2 = ((count_B_q0 == 13'd1) ? 1'b1 : 1'b0);

assign icmp_ln874_fu_779_p2 = ((nibble_K_V_2_fu_769_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln878_14_fu_627_p2 = ((count_BF2_V_fu_164 < num_padd_ops) ? 1'b1 : 1'b0);

assign icmp_ln878_15_fu_954_p2 = (($signed(i_4_fu_176) < $signed(num_padd_ops_cast_reg_1174)) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_621_p2 = ((tmp_fu_611_p4 == 6'd0) ? 1'b1 : 1'b0);

assign lhs_V_7_fu_638_p4 = {{BFIFO_2_dout[42:39]}};

assign lhs_V_fu_654_p4 = {{BFIFO_1176_dout[42:39]}};

assign lnot_i_i_i_fu_920_p2 = ((nibble_K_V_reg_541 == 4'd0) ? 1'b1 : 1'b0);

assign nibble_K_V_1_fu_902_p3 = ((icmp_ln308_fu_896_p2[0:0] == 1'b1) ? trunc_ln301_reg_1147 : nibble_K_V_reg_541);

assign nibble_K_V_2_fu_769_p4 = {{ap_phi_mux_data_V_phi_fu_524_p4[42:39]}};

assign num_padd_ops_cast_fu_926_p1 = num_padd_ops;

assign num_padd_ops_out_din = num_padd_ops;

assign or_ln260_fu_632_p2 = (icmp_ln878_fu_621_p2 | icmp_ln878_14_fu_627_p2);

assign or_ln269_fu_836_p2 = (shl_ln_fu_815_p3 | 5'd1);

assign or_ln282_fu_742_p2 = (shl_ln1_fu_721_p3 | 5'd1);

assign or_ln315_fu_945_p2 = (lnot_i_i_i_fu_920_p2 | icmp_ln315_fu_939_p2);

assign p_Result_1_i_fu_796_p4 = {{p_Val2_1_reg_1093[38:13]}};

assign p_Result_4_i_fu_702_p4 = {{p_Val2_2_reg_1069[38:13]}};

assign p_cast15_i_fu_590_p1 = empty_31_reg_510;

assign p_cast_i_fu_573_p1 = empty_reg_499;

assign ret_V_21_fu_690_p2 = ($signed(zext_ln1347_fu_686_p1) + $signed(14'd16383));

assign ret_V_22_fu_716_p2 = ($signed(lhs_V_7_reg_1077) + $signed(4'd15));

assign ret_V_fu_810_p2 = ($signed(lhs_V_reg_1101) + $signed(4'd15));

assign shl_ln1_fu_721_p3 = {{ret_V_22_fu_716_p2}, {1'd0}};

assign shl_ln_fu_815_p3 = {{ret_V_fu_810_p2}, {1'd0}};

assign start_out = real_start;

assign tmp_3_fu_929_p4 = {{fill_count_q0[31:3]}};

assign tmp_4_fu_886_p4 = {{bcount_q0[31:1]}};

assign tmp_8_i_nbreadreq_fu_202_p3 = BFIFO_2_empty_n;

assign tmp_fu_611_p4 = {{count_BF1_V_fu_168[12:7]}};

assign tmp_i_nbreadreq_fu_194_p3 = BFIFO_1176_empty_n;

assign trunc_ln301_fu_882_p1 = i_reg_530[3:0];

assign trunc_ln674_1_fu_734_p1 = p_Val2_2_reg_1069[12:0];

assign trunc_ln674_2_fu_980_p1 = p_Val2_s_fu_172[38:0];

assign trunc_ln674_fu_828_p1 = p_Val2_1_reg_1093[12:0];

assign zext_ln1347_fu_686_p1 = count_B_q0;

assign zext_ln268_fu_823_p1 = shl_ln_fu_815_p3;

assign zext_ln269_fu_842_p1 = or_ln269_fu_836_p2;

assign zext_ln281_fu_729_p1 = shl_ln1_fu_721_p3;

assign zext_ln282_fu_748_p1 = or_ln282_fu_742_p2;

assign zext_ln358_1_fu_831_p1 = trunc_ln674_fu_828_p1;

assign zext_ln358_2_fu_711_p1 = p_Result_4_i_fu_702_p4;

assign zext_ln358_3_fu_737_p1 = trunc_ln674_1_fu_734_p1;

assign zext_ln358_fu_805_p1 = p_Result_1_i_fu_796_p4;

assign zext_ln708_1_fu_648_p1 = lhs_V_7_fu_638_p4;

assign zext_ln708_fu_664_p1 = lhs_V_fu_654_p4;

assign zext_ln870_fu_682_p1 = add_ln691_fu_675_p2;

always @ (posedge ap_clk) begin
    num_padd_ops_cast_reg_1174[31:13] <= 19'b0000000000000000000;
end

endmodule //msm_arr_bucket_unit_sr_Block_split153_proc7
